public sealed class DEFBJFOKOPM : IEventEmitter
{
	private readonly NEKGJNOFOFN NPIDIMCLNEM;

	public DEFBJFOKOPM(NEKGJNOFOFN NPIDIMCLNEM)
	{
		this.NPIDIMCLNEM = NPIDIMCLNEM;
	}

	void IEventEmitter.Emit(AliasEventInfo FNHCFCAALAE)
	{
		NPIDIMCLNEM.Emit(new AnchorAlias(FNHCFCAALAE.MIDPFGENBCF()));
	}

	void IEventEmitter.Emit(ScalarEventInfo FNHCFCAALAE)
	{
		NPIDIMCLNEM.Emit(new Scalar(FNHCFCAALAE.HCPOJDFJFMM(), FNHCFCAALAE.LOIGCKFONHJ(), FNHCFCAALAE.ICEKHEBNDIN(), FNHCFCAALAE.HALCJLMJDII(), FNHCFCAALAE.BIDLJMEAFMI(), FNHCFCAALAE.NIENIKOPKOG()));
	}

	void IEventEmitter.Emit(LPADMPIAIPF FNHCFCAALAE)
	{
		NPIDIMCLNEM.Emit(new MappingStart(FNHCFCAALAE.HCPOJDFJFMM(), FNHCFCAALAE.LOIGCKFONHJ(), FNHCFCAALAE.BBBGHODAEIN(), FNHCFCAALAE.HALCJLMJDII()));
	}

	void IEventEmitter.Emit(EKKDGIILGMA FNHCFCAALAE)
	{
		NPIDIMCLNEM.Emit(new BLFPJCPALDH());
	}

	void IEventEmitter.Emit(PBGMOJFHMGI FNHCFCAALAE)
	{
		NPIDIMCLNEM.Emit(new JODGINIKFJF(FNHCFCAALAE.HCPOJDFJFMM(), FNHCFCAALAE.LOIGCKFONHJ(), FNHCFCAALAE.BBBGHODAEIN(), FNHCFCAALAE.HALCJLMJDII()));
	}

	void IEventEmitter.Emit(NCGDJIDCIIM FNHCFCAALAE)
	{
		NPIDIMCLNEM.Emit(new AKMKLAINLOL());
	}
}
