using SimpleJSON;
using UnityEngine;

public class KMAENHJICNF
{
	private const string BBFNNDFMHPA = "iOS";

	private const string IHJHAOAFDCO = "Android";

	private const int HDMBLBMAPAM = 0;

	private const int IEBLNGMMCHO = 1;

	private const int NHOLPNBDIPI = 2;

	private static bool OPAHEMMNCOK = true;

	private static JNEBPDNJFJG COGGFPJHLDH;

	public static bool DCHJDPCEODD
	{
		get
		{
			return OPIAGHNCFAM();
		}
		set
		{
			DLDANNALFEA(value);
		}
	}

	public static bool OPIAGHNCFAM()
	{
		return OPAHEMMNCOK;
	}

	public static void DLDANNALFEA(bool value)
	{
		OPAHEMMNCOK = value;
	}

	public static void Init(JNEBPDNJFJG IHLKACMLEGK)
	{
		COGGFPJHLDH = IHLKACMLEGK;
	}

	public static void DCNPKBNNKHD(FIKEKJBAKBO HIKIPCMNPDK)
	{
		DCNPKBNNKHD(HIKIPCMNPDK.JLDEALIEEJI(), HIKIPCMNPDK.JICEOHCLPJP(), HIKIPCMNPDK.KGNGCPEGMJP(), HIKIPCMNPDK.MCDDGNJEKEO());
	}

	public static void DCNPKBNNKHD(string FDKNIPNGFNF, string BGMLFNGKDHI, string DNHKNDPBGNM, string BGLGHEMMANM)
	{
		Debug.LogFormat("Verify: productId={0}, paymentId={1}, receipt={2}, signature={3}", FDKNIPNGFNF, BGMLFNGKDHI, DNHKNDPBGNM, (BGLGHEMMANM == null) ? "null" : BGLGHEMMANM);
		JLDHCFFAIPK jLDHCFFAIPK = null;
		if (!OPAHEMMNCOK || BGMLFNGKDHI == null || ICFMIHIKGOD.LHGPKEFEHDH())
		{
			jLDHCFFAIPK = ICFMIHIKGOD.PHLBLFONMEP(FDKNIPNGFNF, BGMLFNGKDHI, DNHKNDPBGNM, BGLGHEMMANM);
			if (!ICFMIHIKGOD.LHGPKEFEHDH())
			{
				ICFMIHIKGOD.OFFDIMCJOIC().PDEGOEPKGPK(FDKNIPNGFNF);
			}
			ICFMIHIKGOD.OFFDIMCJOIC().NDDCENEGGEA(jLDHCFFAIPK);
		}
		else
		{
			jLDHCFFAIPK = ICFMIHIKGOD.GDFHMOEGPMD(FDKNIPNGFNF, BGMLFNGKDHI, DNHKNDPBGNM, BGLGHEMMANM);
			JJNCKDFPGEA(jLDHCFFAIPK);
		}
	}

	public static void OLDKPFOOPIG(JLDHCFFAIPK PAENLDALDGB)
	{
		if (!OPAHEMMNCOK)
		{
			ICFMIHIKGOD.OFFDIMCJOIC().PDEGOEPKGPK(PAENLDALDGB.JLDEALIEEJI());
			ICFMIHIKGOD.OFFDIMCJOIC().NDDCENEGGEA(PAENLDALDGB);
			ICFMIHIKGOD.NHMONODAIFA(PAENLDALDGB);
		}
		JJNCKDFPGEA(PAENLDALDGB);
	}

	public static void HAFFDGFGHKI(JLDHCFFAIPK PAENLDALDGB)
	{
		NGNFAIBEINJ(PAENLDALDGB);
	}

	private static void JJNCKDFPGEA(JLDHCFFAIPK PAENLDALDGB)
	{
		if (SystemProperties.MEBGOGMJFLM())
		{
			COGGFPJHLDH.VerifyPurchaseAction(PAENLDALDGB, "iOS", EHKCKOMGIBD);
		}
		else if (SystemProperties.IPJFCBAGMJJ())
		{
			COGGFPJHLDH.VerifyPurchaseAction(PAENLDALDGB, "Android", EHKCKOMGIBD);
		}
		if (PAENLDALDGB != null)
		{
			ICFMIHIKGOD.OFFDIMCJOIC().HBDJDPOHEDC(PAENLDALDGB.JLDEALIEEJI(), PAENLDALDGB.KGNGCPEGMJP());
		}
	}

	private static void EHKCKOMGIBD(bool AMKKLMOONEP, string GHDPPHAAPCA, object JHJDJOFPHPH)
	{
		Debug.Log("VerifyRequest_Response");
		Debug.Log((!AMKKLMOONEP) ? "Result fail" : "Result ok!");
		Debug.Log(GHDPPHAAPCA);
		JLDHCFFAIPK jLDHCFFAIPK = (JLDHCFFAIPK)JHJDJOFPHPH;
		if (!AMKKLMOONEP)
		{
			if (jLDHCFFAIPK.LOHAOKIIJOG <= 2)
			{
				jLDHCFFAIPK.LOHAOKIIJOG++;
				JJNCKDFPGEA(jLDHCFFAIPK);
			}
			else
			{
				jLDHCFFAIPK.LOHAOKIIJOG = 0;
				ICFMIHIKGOD.OFFDIMCJOIC().FLKCMDGDLJJ(jLDHCFFAIPK.JLDEALIEEJI());
				ICFMIHIKGOD.OFFDIMCJOIC().MOBENEMFFHG(jLDHCFFAIPK.JLDEALIEEJI(), jLDHCFFAIPK.KGNGCPEGMJP());
			}
			return;
		}
		JSONNode jSONNode = JSONNode.Parse(GHDPPHAAPCA);
		switch (jSONNode["status"].AsInt)
		{
		case 0:
			if (ICFMIHIKGOD.AHJBMFHMAAK(jLDHCFFAIPK))
			{
				jLDHCFFAIPK.LOHAOKIIJOG = 0;
				jLDHCFFAIPK.CCLPNJMEMCG(true);
				ICFMIHIKGOD.OFFDIMCJOIC().KIKKOIHOLLN(jLDHCFFAIPK.JLDEALIEEJI());
				break;
			}
			jLDHCFFAIPK.GEHIBAOABHO(jSONNode["data"]["receiptPurchaseDate"].Value);
			ICFMIHIKGOD.OFFDIMCJOIC().PDEGOEPKGPK(jLDHCFFAIPK.JLDEALIEEJI());
			ICFMIHIKGOD.OFFDIMCJOIC().NDDCENEGGEA(jLDHCFFAIPK);
			ICFMIHIKGOD.KMCDDMLIAOP(jLDHCFFAIPK);
			if (!jSONNode["data"]["confirmed"].AsBool)
			{
				jLDHCFFAIPK.LOHAOKIIJOG = 0;
				NGNFAIBEINJ(jLDHCFFAIPK);
			}
			else
			{
				ICFMIHIKGOD.OICIDLANHHN(jLDHCFFAIPK);
				Debug.Log("Payment doesn't need to be confirm! " + jLDHCFFAIPK.ToString());
			}
			break;
		case 1:
			jLDHCFFAIPK.CCLPNJMEMCG(true);
			ICFMIHIKGOD.AGLGFEGPGHH(jLDHCFFAIPK);
			ICFMIHIKGOD.OFFDIMCJOIC().PDEGOEPKGPK(jLDHCFFAIPK.JLDEALIEEJI());
			ICFMIHIKGOD.OFFDIMCJOIC().KIKKOIHOLLN(jLDHCFFAIPK.JLDEALIEEJI());
			break;
		}
		ICFMIHIKGOD.OFFDIMCJOIC().MOBENEMFFHG(jLDHCFFAIPK.JLDEALIEEJI(), jLDHCFFAIPK.KGNGCPEGMJP());
	}

	private static void NGNFAIBEINJ(JLDHCFFAIPK PAENLDALDGB)
	{
		if (SystemProperties.MEBGOGMJFLM())
		{
			COGGFPJHLDH.ConfirmVerificationAction(PAENLDALDGB, "iOS", EKEOCLDBGNN);
		}
		else if (SystemProperties.IPJFCBAGMJJ())
		{
			COGGFPJHLDH.ConfirmVerificationAction(PAENLDALDGB, "Android", EKEOCLDBGNN);
		}
		if (PAENLDALDGB != null)
		{
			ICFMIHIKGOD.OFFDIMCJOIC().BBBLEFEEMHG(PAENLDALDGB.JLDEALIEEJI(), PAENLDALDGB.KGNGCPEGMJP());
		}
	}

	private static void EKEOCLDBGNN(bool AMKKLMOONEP, string GHDPPHAAPCA, object JHJDJOFPHPH)
	{
		Debug.Log("CompletedRequest_Response");
		Debug.Log((!AMKKLMOONEP) ? "Result fail" : "Result ok!");
		Debug.Log(GHDPPHAAPCA);
		JLDHCFFAIPK jLDHCFFAIPK = (JLDHCFFAIPK)JHJDJOFPHPH;
		if (!AMKKLMOONEP)
		{
			if (jLDHCFFAIPK.LOHAOKIIJOG <= 2)
			{
				jLDHCFFAIPK.LOHAOKIIJOG++;
				NGNFAIBEINJ(jLDHCFFAIPK);
			}
			else
			{
				jLDHCFFAIPK.LOHAOKIIJOG = 0;
				ICFMIHIKGOD.OFFDIMCJOIC().IIBFMAEJEOA(jLDHCFFAIPK.JLDEALIEEJI(), jLDHCFFAIPK.KGNGCPEGMJP());
			}
		}
		else
		{
			ICFMIHIKGOD.OICIDLANHHN(jLDHCFFAIPK);
			ICFMIHIKGOD.OFFDIMCJOIC().IIBFMAEJEOA(jLDHCFFAIPK.JLDEALIEEJI(), jLDHCFFAIPK.KGNGCPEGMJP());
		}
	}
}
