public class SwitchForm
{
	public string IDString;

	public EGGHFJMOPCE Type;

	public bool Multi;

	public int DJIJIHHBHHP;

	public int BEIECNAFPJJ;

	public string HKJPFMBPOJO;

	public SwitchForm(string FBEJCDFPDLD, EGGHFJMOPCE LFLGCDNKNJI, bool IJMDFIKBJAG, int GNKCLPKOEBL, int FJLKBBJCLHD, string PHBJBABMEPL)
	{
		IDString = FBEJCDFPDLD;
		Type = LFLGCDNKNJI;
		Multi = IJMDFIKBJAG;
		DJIJIHHBHHP = GNKCLPKOEBL;
		BEIECNAFPJJ = FJLKBBJCLHD;
		HKJPFMBPOJO = PHBJBABMEPL;
	}

	public SwitchForm(string FBEJCDFPDLD, EGGHFJMOPCE LFLGCDNKNJI, bool IJMDFIKBJAG, int GNKCLPKOEBL)
		: this(FBEJCDFPDLD, LFLGCDNKNJI, IJMDFIKBJAG, GNKCLPKOEBL, 0, string.Empty)
	{
	}

	public SwitchForm(string FBEJCDFPDLD, EGGHFJMOPCE LFLGCDNKNJI, bool IJMDFIKBJAG)
		: this(FBEJCDFPDLD, LFLGCDNKNJI, IJMDFIKBJAG, 0)
	{
	}
}
