-- GENERATED by Tools/GenerateDE128ChallengerText.py; do not edit by hand.
local sf2 = require("sf2")
-- Text lives in localizations/<language>.toml.
local text = {}
for _, key in ipairs({
    "FISHER_Title",
    "Fisher_drop",
    "HAWK_Title",
    "Hawk_drop",
    "NAME_FISHER",
    "NAME_HAWK",
    "NAME_IM_STRANGER",
    "NAME_OUTCAST",
    "NAME_RONIN",
    "NAME_ROSE",
    "NAME_TRICKSTER",
    "NOVA_Title",
    "Nova_drop",
    "OK",
    "OUTCAST_Title",
    "Outcast_drop",
    "RONIN_Title",
    "ROSE_Title",
    "Ronin_drop",
    "Rose_drop",
    "TRICKSTER_Title",
    "Trickster_drop",
    "WEAPON_DADAO_JANISSARY",
    "WEAPON_HEAVY_KUSARIGAMA",
    "WEAPON_KATANA",
    "WEAPON_NAGINATA",
    "WEAPON_NUNCHAKU",
    "WEAPON_STRANGER_KNUCKLES",
    "WEAPON_WANDERER_STAFF",
    "characterTrickster",
    "descFisher",
    "descHawk",
    "descNova",
    "descOutcast",
    "descRonin",
    "descRose",
    "descTrickster",
}) do
    text[key] = sf2.localization.key("challenger." .. key)
end
-- Battle and opponent fields take the qualified runtime key, not a handle.
function text.key(key)
    assert(text[key], "Unknown Challenger text key " .. tostring(key))
    return (sf2.mod.id .. ":localization/challenger." .. key):lower()
end
return text
