-- Generated by Tools/ImportDE128MenuArt.py.
local sf2 = require("sf2")
local replacements = {
    { "core:ui/atlases/menubuttons.btn_disciple", "sprites/menu/menubuttons.btn_disciple" },
    { "core:ui/atlases/menubuttons.btn_punching_bag", "sprites/menu/menubuttons.btn_punching_bag" },
    { "core:ui/atlases/menubuttons.dojo_active", "sprites/menu/menubuttons.dojo_active" },
    { "core:ui/atlases/menubuttons.dojo_normal", "sprites/menu/menubuttons.dojo_normal" },
    { "core:ui/atlases/menubuttons.highlight_menu", "sprites/menu/menubuttons.highlight_menu" },
    { "core:ui/atlases/menubuttons.map_active", "sprites/menu/menubuttons.map_active" },
    { "core:ui/atlases/menubuttons.map_normal", "sprites/menu/menubuttons.map_normal" },
    { "core:ui/atlases/menubuttons.profile_active", "sprites/menu/menubuttons.profile_active" },
    { "core:ui/atlases/menubuttons.profile_normal", "sprites/menu/menubuttons.profile_normal" },
    { "core:ui/atlases/menubuttons.settings_active", "sprites/menu/menubuttons.settings_active" },
    { "core:ui/atlases/menubuttons.settings_normal", "sprites/menu/menubuttons.settings_normal" },
    { "core:ui/atlases/menubuttons.shop_active", "sprites/menu/menubuttons.shop_active" },
    { "core:ui/atlases/menubuttons.shop_normal", "sprites/menu/menubuttons.shop_normal" },
    { "core:ui/fullscreen/vs_fon_left.img", "sprites/menu/vs_fon_left" },
    { "core:ui/fullscreen/vs_fon_right.img", "sprites/menu/vs_fon_right" },
}
for _, row in ipairs(replacements) do
    sf2.assets.replace { target = row[1], replacement = row[2] }
end
