local sf2 = require("sf2")
-- Historical DE values copied offline. The runtime reads only this Lua module.
local values = {
    cro = {
        ["characterSensei"] = "SENSEI",
        ["OK"] = "OK",
        ["Sensei_defeat1"] = "Ne, stani, sve je bilo sasvim drukčije... Oprosti starcu, zaboravio sam.",
        ["Sensei_defeat2"] = "Čini se da je sve išlo drugačije... Sjećanje je vrlo krhka stvar.",
        ["Sensei_defeat3"] = "Čini mi se da je kraj tog okršaja bio drukčiji. Pokušat ću se sjetiti...",
        ["Sensei_defeat4"] = "Moja sjećanja su tako mutna... Čini mi se da sam pobijedio u toj borbi.",
        ["Sensei_defeat5"] = "Ne, nije tako. Tada sam pobijedio.",
    },
    eng = {
        ["characterSensei"] = "SENSEI",
        ["OK"] = "OK",
        ["Sensei_defeat1"] = "No, wait... It didn’t happen that way... Please forgive the old man’s forgetfulness.",
        ["Sensei_defeat2"] = "I think it happened another way... Memories can be very fragile.",
        ["Sensei_defeat3"] = "I think that wasn’t how that fight ended. Let me try to recall it...",
        ["Sensei_defeat4"] = "My memories are so vague... I think I won that fight.",
        ["Sensei_defeat5"] = "No, it wasn’t that way. It seems like I won then... likely.",
    },
    fra = {
        ["characterSensei"] = "SENSEI",
        ["OK"] = "OK",
        ["Sensei_defeat1"] = "Non, attends... Les choses se sont déroulées autrement... Pardonne la mémoire vacillante d'un vieillard.",
        ["Sensei_defeat2"] = "Je crois que ça ne s'est pas passé ainsi... Les souvenirs sont fugaces.",
        ["Sensei_defeat3"] = "Je ne pense pas que le combat se soit terminé de cette manière ! Laisse-moi puiser en mes souvenirs...",
        ["Sensei_defeat4"] = "Mes souvenirs sont si vagues... Je crois avoir remporté ce combat.",
        ["Sensei_defeat5"] = "Non, ça s'est déroulé autrement. Je pense avoir gagné...",
    },
    ger = {
        ["characterSensei"] = "SENSEI",
        ["OK"] = "OK",
        ["Sensei_defeat1"] = "Nein, warte ... So war es nicht ... Bitte vergib die Vergesslichkeit eines alten Mannes.",
        ["Sensei_defeat2"] = "Ich glaube, es war anders ... Das Gedächtnis spielt mir oft einen Streich.",
        ["Sensei_defeat3"] = "Ich glaube, das war nicht das Ende dieses Kampfes. Lass mich noch einmal nachdenken ...",
        ["Sensei_defeat4"] = "Meine Erinnerungen sind so verschwommen ... Ich glaube, ich habe diesen Kampf gewonnen.",
        ["Sensei_defeat5"] = "Nein, so war es nicht. Offenbar habe ich dann gewonnen ... wahrscheinlich.",
    },
    hin = {
        ["characterSensei"] = "सेंसी",
        ["OK"] = "ठीक है",
        ["Sensei_defeat1"] = "नहीं, रुको... ऐसा नहीं हुआ था... कृपया इस बूढ़े आदमी के भुलक्कड़पन को क्षमा करें।",
        ["Sensei_defeat2"] = "मुझे लगता है कि यह किसी और तरह से हुआ था... यादें बहुत नाजुक हो सकती हैं।",
        ["Sensei_defeat3"] = "मुझे लगता है कि उस लड़ाई का अंत इस तरह नहीं हुआ था। मुझे इसे याद करने की कोशिश करने दो...",
        ["Sensei_defeat4"] = "मेरी यादें बहुत धुंधली हैं... मुझे लगता है कि मैं वह लड़ाई जीत गया था।",
        ["Sensei_defeat5"] = "नहीं, ऐसा नहीं था। ऐसा लगता है कि मैं तब जीत गया था... शायद।",
    },
    hun = {
        ["characterSensei"] = "SENSEI",
        ["OK"] = "OK",
        ["Sensei_defeat1"] = "Nem, várj... Ez nem így történt... Kérlek, bocsásd meg egy öregember feledékenységét.",
        ["Sensei_defeat2"] = "Szerintem ez másképp történt... Az emlékek nagyon törékenyek tudnak lenni.",
        ["Sensei_defeat3"] = "Azt hiszem, a küzdelem nem így végződött. Hadd próbáljam meg felidézni...",
        ["Sensei_defeat4"] = "Az emlékeim olyan homályosak... Úgy rémlik, megnyertem azt a harcot.",
        ["Sensei_defeat5"] = "Nem, nem így volt. Úgy tűnik, akkor én győztem... valószínűleg.",
    },
    ita = {
        ["characterSensei"] = "SENSEI",
        ["OK"] = "OK",
        ["Sensei_defeat1"] = "No, aspetta... Non è stato proprio così... Perdonami, sono vecchio e la mia memoria non è più quella di un tempo.",
        ["Sensei_defeat2"] = "Penso che non sia andata proprio così... A volte i ricordi sono piuttosto confusi.",
        ["Sensei_defeat3"] = "Non mi sembra che il combattimento sia terminato così. Lascia che provi a ricordare meglio...",
        ["Sensei_defeat4"] = "I miei ricordi sono molto vaghi... Penso di aver vinto quel combattimento.",
        ["Sensei_defeat5"] = "No, mi sono sbagliato. Mi sembra di aver vinto... dev'essere così.",
    },
    kor = {
        ["characterSensei"] = "센세이",
        ["OK"] = "확인",
        ["Sensei_defeat1"] = "아니, 잠깐... 이런 게 아니었는데... 이 늙은이의 건망증을 용서해주게.",
        ["Sensei_defeat2"] = "달랐던 것 같은데... 기억은 헷갈릴 수 있거든.",
        ["Sensei_defeat3"] = "이렇게 대결이 끝난 것 같지는 않은데... 다시 기억을 더듬어 보지...",
        ["Sensei_defeat4"] = "기억이 흐릿해서... 내가 그 싸움에서 이겼던 것 같은데.",
        ["Sensei_defeat5"] = "아니, 이게 아니었다네. 내가 이긴 다음... 음, 그랬던 것 같다네.",
    },
    por = {
        ["characterSensei"] = "SENSEI",
        ["OK"] = "OK",
        ["Sensei_defeat1"] = "Não, espere... Não foi assim que aconteceu. Por favor, perdoe o esquecimento deste velho.",
        ["Sensei_defeat2"] = "Acho que aconteceu de outro jeito... A memória pode ser muito frágil.",
        ["Sensei_defeat3"] = "Acho que não foi assim que a luta terminou. Deixe-me tentar lembrar...",
        ["Sensei_defeat4"] = "Minhas lembranças são tão vagas... Eu acho que venci aquela luta.",
        ["Sensei_defeat5"] = "Não, não foi assim. Parece que eu venci... eu acho.",
    },
    rom = {
        ["characterSensei"] = "SENSEI",
        ["OK"] = "OK",
        ["Sensei_defeat1"] = "Nu, stai... Nu s-a întâmplat așa... Te rog să ierţi uitarea bătrânului.",
        ["Sensei_defeat2"] = "Cred că s-a întâmplat altfel... Amintirile pot fi foarte fragile.",
        ["Sensei_defeat3"] = "Cred că nu așa s-a terminat acea luptă. Lasă-mă să încerc să mi-o amintesc...",
        ["Sensei_defeat4"] = "Amintirile mele sunt atât de vagi... Cred că am câștigat acea luptă.",
        ["Sensei_defeat5"] = "Nu, nu a fost așa. Se pare că am câștigat atunci... probabil.",
    },
    rus = {
        ["characterSensei"] = "СЭНСЕЙ",
        ["OK"] = "ОК",
        ["Sensei_defeat1"] = "Нет, постой, все было совсем иначе... Прости старика, запамятовал.",
        ["Sensei_defeat2"] = "Кажется, все было по-другому... Память — очень хрупкая штука.",
        ["Sensei_defeat3"] = "Кажется, финал той схватки был иным. Попробую вспомнить...",
        ["Sensei_defeat4"] = "Мои воспоминания такие расплывчатые... Мне кажется, я выиграл тот бой.",
        ["Sensei_defeat5"] = "Нет, не так. В тот раз я победил.",
    },
    spa = {
        ["characterSensei"] = "SENSEI",
        ["OK"] = "VALE",
        ["Sensei_defeat1"] = "No, espera... No ocurrió así... Disculpa la mala memoria del anciano.",
        ["Sensei_defeat2"] = "Creo que ocurrió de otra forma... Los recuerdos pueden ser muy frágiles.",
        ["Sensei_defeat3"] = "Creo que no fue así como acabó la lucha. Déjame que trate de recordar...",
        ["Sensei_defeat4"] = "Mis recuerdos son tan borrosos... Creo que gané esa batalla.",
        ["Sensei_defeat5"] = "No, no fue así. Me parece que gané... Es probable.",
    },
    swe = {
        ["characterSensei"] = "SENSEI",
        ["OK"] = "OK",
        ["Sensei_defeat1"] = "Nej, vänta... Det gick inte till på det viset... Ursäkta en gammal mans glömska.",
        ["Sensei_defeat2"] = "Jag tror det hände på ett annat sätt... Minnen kan vara väldigt bräckliga.",
        ["Sensei_defeat3"] = "Jag tror inte att det var så den striden slutade. Låt mig försöka minnas...",
        ["Sensei_defeat4"] = "Mina minnen är så vaga... Jag tror att jag vann den striden.",
        ["Sensei_defeat5"] = "Nej, det var inte så. Det verkar som om jag vann då... troligtvis.",
    },
    tur = {
        ["characterSensei"] = "SENSEY",
        ["OK"] = "TAMAM",
        ["Sensei_defeat1"] = "Hayır, bekle... O şekilde olmadı... Lütfen bu yaşlı adamın unutkanlığını bağışla.",
        ["Sensei_defeat2"] = "Bence başka bir şekilde oldu... Hatıralar çok kırılgan olabiliyor.",
        ["Sensei_defeat3"] = "Sanki sonu öyle bitmemişti. Müsaade edersen son kısmı tekrar hatırlamak isterim...",
        ["Sensei_defeat4"] = "Hatıralarım çok belirsiz... Sanırım o dövüşü ben kazanmıştım.",
        ["Sensei_defeat5"] = "Hayır, öyle olmamıştı. Ben kazanmıştım... galiba.",
    },
}
local text = {}
for language, entries in pairs(values) do
    for key, value in pairs(entries) do
        text[key] = sf2.localization.register { id = "sensei.defeat." .. key, language = language, value = value }
    end
end
return text
