local sf2 = require("sf2")
-- Text lives in localizations/<language>.toml.
local text = {}
for _, key in ipairs({
    "ActScreenSensei1",
    "ActScreenSensei2",
    "ActScreenSensei3",
    "ActScreenSensei4",
    "ActScreenSensei5",
    "ActScreenSensei6",
    "ButcherYoung_Greetings",
    "Butcher_zone3_1",
    "Butcher_zone3_2",
    "Guard1_Butcher_Sensei",
    "Guard1_Hermit_Sensei",
    "Guard1_Lynx_Sensei",
    "Guard1_Wasp_Sensei",
    "Guard1_Widow_Sensei",
    "Guard2_Butcher_Sensei",
    "Guard2_Hermit_Sensei",
    "Guard2_Lynx_Sensei",
    "Guard2_Wasp_Sensei",
    "Guard2_Widow_Sensei",
    "HermitYoung_Greetings",
    "Hermit_zone2_1",
    "Hermit_zone2_2",
    "LynxYoung_Greetings",
    "Lynx_Sensei_1",
    "Lynx_Sensei_2",
    "Lynx_Sensei_3",
    "NAME_BUTCHER",
    "NAME_HERMIT",
    "NAME_LYNX",
    "NAME_PRINCE",
    "NAME_SHOGUN",
    "NAME_WASP",
    "NAME_WIDOW",
    "OK",
    "Prince_Intro",
    "Prince_zone3_1",
    "Prince_zone6_1",
    "Prince_zone6_2",
    "Sensei_arc_intro1",
    "Sensei_zone3_1",
    "Sensei_zone4_1",
    "Sensei_zone6_1",
    "Shogun_zone6_1",
    "TITLE_PRINCE_EVIL",
    "WaspYoung_Greetings",
    "Wasp_zone4_1",
    "Wasp_zone4_2",
    "WidowYoung_Greetings",
    "Widow_zone5_1",
    "Widow_zone5_2",
    "Zone2_SenseiReminder",
    "Zone3_SenseiReminder",
    "Zone4_SenseiReminder",
    "Zone5_SenseiReminder",
    "Zone6_SenseiReminder",
    "characterSensei",
    "character_Asian",
    "character_Blind",
    "character_Fanatic",
    "character_Indean",
    "character_Philosopher",
    "character_Pirate",
    "character_Ronin",
    "character_Sadist",
    "character_Savage",
    "character_Sister",
    "dlgStoryBtnFight",
}) do
    text[key] = sf2.localization.key("sensei.entry." .. key)
end
return text
