-- GENERATED by Tools/GenerateDE128TitanRewardText.py; do not edit by hand.
local sf2 = require("sf2")
-- Text lives in localizations/<language>.toml.
local text = {}
for _, key in ipairs({
    "BODY_TITAN",
    "HEAD_TITAN",
    "MAGIC_MIND_THROW",
    "RANGED_TITANS_HARPOON",
}) do
    text[key] = sf2.localization.key("titan_reward." .. key)
end
return text
