-- GENERATED by Tools/GenerateDE128TitanRewardText.py; do not edit by hand.
return {
    cro = {
        BODY_TITAN = "Titanov oblik",
        HEAD_TITAN = "Titanova kaciga",
        RANGED_TITANS_HARPOON = "Titanov harpun",
        MAGIC_MIND_THROW = "Titanovo bacanje umom",
    },
    eng = {
        BODY_TITAN = "Titan’s Form",
        HEAD_TITAN = "Titan’s Helm",
        RANGED_TITANS_HARPOON = "Titan’s Harpoon",
        MAGIC_MIND_THROW = "Titan’s Mind Throw",
    },
    fra = {
        BODY_TITAN = "Forme du Titan",
        HEAD_TITAN = "Heaume de Titan",
        RANGED_TITANS_HARPOON = "Harpon de Titan",
        MAGIC_MIND_THROW = "Projection mentale de Titan",
    },
    ger = {
        BODY_TITAN = "Titans Gestalt",
        HEAD_TITAN = "Titans Helm",
        RANGED_TITANS_HARPOON = "Titans Harpune",
        MAGIC_MIND_THROW = "Titans Gedankenwurf",
    },
    hin = {
        BODY_TITAN = "टाइटन का रूप",
        HEAD_TITAN = "टाइटन का हेलमेट",
        RANGED_TITANS_HARPOON = "टाइटन का हार्पून",
        MAGIC_MIND_THROW = "टाइटन का माइंड थ्रो",
    },
    hun = {
        BODY_TITAN = "Titán alakja",
        HEAD_TITAN = "Titán sisakja",
        RANGED_TITANS_HARPOON = "Titán szigonya",
        MAGIC_MIND_THROW = "Titán elmedobás",
    },
    ita = {
        BODY_TITAN = "Forma del Titano",
        HEAD_TITAN = "Elmo di Titan",
        RANGED_TITANS_HARPOON = "Arpione di Titan",
        MAGIC_MIND_THROW = "Lancio Mentale di Titan",
    },
    kor = {
        BODY_TITAN = "타이탄의 형상",
        HEAD_TITAN = "타이탄의 투구",
        RANGED_TITANS_HARPOON = "타이탄의 작살",
        MAGIC_MIND_THROW = "타이탄의 마인드 스로우",
    },
    por = {
        BODY_TITAN = "Forma do Titã",
        HEAD_TITAN = "Elmo de Titã",
        RANGED_TITANS_HARPOON = "Arpão de Titã",
        MAGIC_MIND_THROW = "Arremesso Mental de Titã",
    },
    rom = {
        BODY_TITAN = "Forma lui Titan",
        HEAD_TITAN = "Casca lui Titan",
        RANGED_TITANS_HARPOON = "Harponul lui Titan",
        MAGIC_MIND_THROW = "Aruncarea Mentală a lui Titan",
    },
    rus = {
        BODY_TITAN = "Форма Титана",
        HEAD_TITAN = "Шлем Титана",
        RANGED_TITANS_HARPOON = "Хват Титана",
        MAGIC_MIND_THROW = "Подавление разума Титаном",
    },
    spa = {
        BODY_TITAN = "Forma del Titán",
        HEAD_TITAN = "Casco de Titán",
        RANGED_TITANS_HARPOON = "Arpón de Titán",
        MAGIC_MIND_THROW = "Lanzamiento mental de Titán",
    },
    swe = {
        BODY_TITAN = "Titanens gestalt",
        HEAD_TITAN = "Titans hjälm",
        RANGED_TITANS_HARPOON = "Titans harpun",
        MAGIC_MIND_THROW = "Titans tankekast",
    },
    tur = {
        BODY_TITAN = "Titan Formu",
        HEAD_TITAN = "Titan'ın Miğferi",
        RANGED_TITANS_HARPOON = "Titan'ın Zıpkını",
        MAGIC_MIND_THROW = "Titan'ın Zihin Fırlatması",
    },
}
