-- GENERATED by Tools/GenerateDE128Underworld.py from reviewed DE sources; do not edit by hand.
return {
    unlock_fight = "core:fights/zone_1/boss_lynx/2",
    focus = "BOSS_1",
    intro = {
        {
            lines = {
                { text = "ActScreenRaid", frames = 240 },
            },
        },
        { title = "RAIDBOSS_FIRE", text = "dlgRaidIntro1", portrait = "boss_fire", button = "dlgStoryBtnMore" },
        { title = "RAIDBOSS_FIRE", text = "dlgRaidIntro2", portrait = "boss_fire", button = "OK" },
    },
    followup = {
        { title = "characterMay", text = "dlgRaidStory1", portrait = "character_may_1", button = "dlgStoryBtnMore" },
        { title = "characterSensei", text = "dlgRaidStory2", portrait = "character_sensei", button = "dlgStoryBtnMore" },
        { title = "characterMay", text = "dlgRaidStory3", portrait = "character_may_1", button = "dlgStoryBtnMore" },
        { title = "characterSensei", text = "dlgRaidStory4", portrait = "character_sensei", button = "dlgStoryBtnMore", scene = "dojo" },
    },
    bosses = {
        BOSS_1 = {
            enter = {
                { title = "characterMay", text = "dlgVolcanoStory1", portrait = "character_may_1", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlgVolcanoStory2", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_FIRE", text = "dlgVolcanoGreetings", portrait = "boss_fire", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_FIRE", text = "dlgVolcanoWin", portrait = "boss_fire", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_FIRE", text = "dlgVolcanoLost", portrait = "boss_fire", button = "OK" },
            },
        },
        BOSS_2 = {
            enter = {
                { title = "RAIDBOSS_Stone", text = "dlgMegalithGreetings", portrait = "boss_crystal", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_Stone", text = "dlgMegalithWin", portrait = "boss_crystal", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_Stone", text = "dlgMegalithLost", portrait = "boss_crystal", button = "OK" },
            },
        },
        BOSS_PUPPETEER = {
            enter = {
                { title = "tutorial_ascention_intro_title", text = "dlgIndia24_Enter_Puppet_1", portrait = "character_puppeteer", button = "dlgStoryBtnMore" },
                { title = "CharacterIndia24Nrityu", text = "dlgIndia24_Story_Win_Nrityu_1", portrait = "character_nrityu", button = "dlgStoryBtnMore" },
                { title = "tutorial_ascention_intro_title", text = "dlgIndia24_Story_Win_Puppet_4", portrait = "character_puppeteer", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "tutorial_ascention_intro_title", text = "dlgIndia24_Story_Loose_Puppet_3", portrait = "character_puppeteer", button = "OK" },
            },
            win = {
                { title = "tutorial_ascention_intro_title", text = "dlgIndia24_Story_Win_Puppet_6", portrait = "character_puppeteer", button = "OK" },
            },
        },
        BOSS_3 = {
            enter = {
                { title = "RAIDBOSS_Mushroom", text = "dlgFungusGreetings", portrait = "boss_mushroom", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_Mushroom", text = "dlgFungusWin", portrait = "boss_mushroom", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_Mushroom", text = "dlgFungusLost", portrait = "boss_mushroom", button = "OK" },
            },
        },
        BOSS_LAMB_VULCAN = {
            enter = {
                { title = "characterMiniEventPriestess", text = "MiniEventVulkanStory_1", portrait = "character_pristess", button = "dlgStoryBtnMore" },
                { title = "characterMiniEventPriestess", text = "MiniEventVulkanStory_2", portrait = "character_pristess", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_LAMB", text = "MiniEventVulkanFight_Enter_1", portrait = "boss_lamb_vulcan", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_LAMB", text = "MiniEventVulkan_Loss_1", portrait = "boss_lamb_vulcan", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_LAMB", text = "MiniEventVulkan_Win_1", portrait = "boss_lamb_vulcan", button = "OK" },
            },
        },
        BOSS_4 = {
            enter = {
                { title = "RAIDBOSS_Vortex", text = "dlgVortexGreetings", portrait = "boss_vortex", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_Vortex", text = "dlgVortexWin", portrait = "boss_vortex", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_Vortex", text = "dlgVortexLost", portrait = "boss_vortex", button = "OK" },
            },
        },
        BOSS_5 = {
            enter = {
                { title = "RAIDBOSS_Fatum", text = "dlgFatumGreetings", portrait = "boss_fatum", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlgFatumStory1", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_Fatum", text = "dlgFatumStory2", portrait = "boss_fatum", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_Fatum", text = "dlgFatumWin", portrait = "boss_fatum", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_Fatum", text = "dlgFatumLost", portrait = "boss_fatum", button = "OK" },
            },
        },
        BOSS_LAMB_FUNGUS = {
            enter = {
                { text = "MiniEventAnnounce", button = "dlgStoryBtnMore" },
                { title = "characterMiniEventPriestess", text = "MiniEventStory_1", portrait = "character_pristess", button = "dlgStoryBtnMore" },
                { title = "characterMiniEventPriestess", text = "MiniEventStory_2", portrait = "character_pristess", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_LAMB", text = "MiniEventStory_EnterBattle", portrait = "boss_lamb_fungus", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_LAMB", text = "MiniEventStory_Loss_1", portrait = "boss_lamb_fungus", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_LAMB", text = "MiniEventStory_Win_1", portrait = "boss_lamb_fungus", button = "OK" },
            },
        },
        BOSS_WOLF_WIND = {
            enter = {
                { title = "characterSensei", text = "dlgAmericanEvent22Story_Sensei_1", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "NAME_PUMA", text = "dlgAmericanEvent22Story_Puma_1", portrait = "character_puma", button = "dlgStoryBtnMore" },
                { title = "characterMay", text = "dlgAmericanEvent22Story_May_1", portrait = "character_may_1", button = "dlgStoryBtnMore" },
                { title = "NAME_PUMA", text = "dlgAmericanEvent22Story_Puma_2", portrait = "character_puma", button = "dlgStoryBtnMore" },
                { title = "NAME_PUMA", text = "dlgAmericanEvent22Story_Puma_3", portrait = "character_puma", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_WIND_WOLF_TITLE", text = "dlgAmericanEvent22Story_Wind_Wolf_1", portrait = "boss_wind_wolf_new", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlgAmericanEvent22Story_Sensei_2", portrait = "character_sensei", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_WIND_WOLF_TITLE", text = "dlgAmericanEvent22Story_Wind_Wolf_Lose", portrait = "boss_wind_wolf_new", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_WIND_WOLF_TITLE", text = "dlgAmericanEvent22Story_Wind_Wolf_Win_1", portrait = "boss_wind_wolf_new", button = "OK" },
            },
        },
        BOSS_6 = {
            enter = {
                { title = "RAIDBOSS_Arkhos", text = "dlgArkhosGreetings", portrait = "boss_arkhos", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlgArkhosStory1", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_Arkhos", text = "dlgArkhosStory2", portrait = "boss_arkhos", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_Arkhos", text = "dlgArkhosWin", portrait = "boss_arkhos", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_Arkhos", text = "dlgArkhosLost", portrait = "boss_arkhos", button = "OK" },
            },
        },
        BOSS_7 = {
            enter = {
                { title = "RAIDBOSS_Hoaxen", text = "dlgHoaxenGreetings", portrait = "boss_hoaxen", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlgHoaxenStory1", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_Hoaxen", text = "dlgHoaxenStory2", portrait = "boss_hoaxen", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_Hoaxen", text = "dlgHoaxenWin", portrait = "boss_hoaxen", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_Hoaxen", text = "dlgHoaxenLost", portrait = "boss_hoaxen", button = "OK" },
            },
        },
        BOSS_8 = {
            enter = {
                { title = "RAIDBOSS_Hunger", text = "Hunger_Greetings1", portrait = "boss_hunger", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "Hunger_Greetings2", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_Hunger", text = "Hunger_Greetings3", portrait = "boss_hunger", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_Hunger", text = "Hunger_AfterLoss", portrait = "boss_hunger", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_Hunger", text = "Hunger_AfterWin", portrait = "boss_hunger", button = "OK" },
            },
        },
        BOSS_LAMB_HUNGER = {
            enter = {
                { text = "MiniEventAnnounce", button = "dlgStoryBtnMore" },
                { title = "characterMiniEventPriestess", text = "MiniEventHungerStory_1", portrait = "character_pristess", button = "dlgStoryBtnMore" },
                { title = "characterMiniEventPriestess", text = "MiniEventHungerStory_2", portrait = "character_pristess", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_LAMB", text = "MiniEventHungerFight_Enter_1", portrait = "boss_lamb_hunger", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_LAMB", text = "MiniEventHunger_Loss_1", portrait = "boss_lamb_hunger", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_LAMB", text = "MiniEventHunger_Win_1", portrait = "boss_lamb_hunger", button = "OK" },
            },
        },
        BOSS_9 = {
            enter = {
                { title = "RAIDBOSS_War", text = "War_Greetings1", portrait = "boss_war", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "War_Greetings2", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_War", text = "War_Greetings3", portrait = "boss_war", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_War", text = "War_AfterLoss", portrait = "boss_war", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_War", text = "War_AfterWin", portrait = "boss_war", button = "OK" },
            },
        },
        BOSS_10 = {
            enter = {
                { title = "RAIDBOSS_Tenebris", text = "Tenebris_greetings_1", portrait = "boss_tenebris", ignore_back = true, button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "Tenebris_greetings_2", portrait = "character_sensei", ignore_back = true, button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_Tenebris", text = "Tenebris_greetings_3", portrait = "boss_tenebris", ignore_back = true, button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "Tenebris_greetings_4", portrait = "character_sensei", ignore_back = true, button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_Tenebris", text = "Tenebris_wins", portrait = "boss_tenebris", ignore_back = true, button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_Tenebris", text = "Tenebris_loses", portrait = "boss_tenebris", ignore_back = true, button = "dlgStoryBtnMore" },
            },
        },
        BOSS_ARCHITECT_1 = {
            enter = {
                { title = "RAIDBOSS_ARCHITECT", text = "summerfest25_story2_1", portrait = "boss_architect_hummer", button = "dlgStoryBtnMore" },
                { title = "character_Blind", text = "summerfest25_story2_2", portrait = "Boss_Ermin", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_ARCHITECT", text = "summerfest25_story2_3", portrait = "boss_architect_hummer", button = "dlgStoryBtnMore" },
                { title = "character_Blind", text = "summerfest25_story2_4", portrait = "Boss_Ermin", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_ARCHITECT", text = "summerfest25_story2_5", portrait = "boss_architect_hummer", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "summerfest25_story2_6", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "summerfest25_story2_7", portrait = "character_sensei", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_ARCHITECT", text = "summerfest25_story2_defeat_1", portrait = "boss_architect_hummer", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_ARCHITECT", text = "summerfest25_story2_win_1", portrait = "boss_architect_hummer", button = "OK" },
            },
        },
        BOSS_11 = {
            enter = {
                {
                    lines = {
                        { text = "EnterPortal_ActScreen", frames = 300 },
                    },
                },
                { title = "characterMay", text = "Gatekeeper_greetings_Assistant_1", portrait = "character_may_4", button = "dlgStoryBtnMore" },
                { title = "characterMay", text = "Gatekeeper_greetings_Assistant_2", portrait = "character_may_4", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_GATEKEEPER", text = "Gatekeeper_greetings_1", portrait = "boss_gatekeeper", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "Gatekeeper_greetings_Sensei", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_GATEKEEPER", text = "Gatekeeper_greetings_2", portrait = "boss_gatekeeper", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "Gatekeeper_greetings_Sensei_2", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "characterMay", text = "Gatekeeper_greetings_Assistant_3", portrait = "character_may_3", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "Gatekeeper_greetings_Sensei_3", portrait = "character_sensei", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_SAIMON", text = "Gatekeeper_lost_Saimon", portrait = "character_simon_raid", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_SAIMON", text = "Gatekeeper_win_Saimon", portrait = "character_simon_raid", button = "OK" },
            },
        },
        BOSS_ARCHITECT_2 = {
            enter = {
                { title = "tutorial_ascention_intro_title", text = "dlgHW22StoryPuppeteer_1", portrait = "character_puppeteer", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlgHW22StorySensei_1", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "tutorial_ascention_intro_title", text = "dlgHW22StoryPuppeteer_2", portrait = "character_puppeteer", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlgHW22StorySensei_2", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "tutorial_ascention_intro_title", text = "dlgHW22StoryPuppeteer_3", portrait = "character_puppeteer", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_ARCHITECT", text = "dlgHW22StoryArchitect_1", portrait = "boss_architect", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_ARCHITECT", text = "dlgHW22StoryArchitect_2", portrait = "boss_architect", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlgHW22StorySensei_3", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_ARCHITECT", text = "dlgHW22EnterArchitect", portrait = "boss_architect", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_ARCHITECT", text = "dlgHW22LooseArchitect_1", portrait = "boss_architect", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_ARCHITECT", text = "dlgHW22WinArchitect_1", portrait = "boss_architect", button = "OK" },
            },
        },
        BOSS_12 = {
            enter = {
                { title = "RAIDBOSS_SAIMON", text = "saturn_greeting_saimon_1", portrait = "character_simon_raid", button = "dlgStoryBtnMore" },
                { title = "characterMay", text = "saturn_greetingn_May_1", portrait = "character_may_3", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_SAIMON", text = "saturn_greeting_saimon_2", portrait = "character_simon_raid", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_SATURN_TITLE", text = "saturn_greeting_saturn_1", portrait = "boss_saturn", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_SAIMON", text = "saturn_greeting_saimon_3", portrait = "character_simon_raid", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_SATURN_TITLE", text = "saturn_enter_saturn_1", portrait = "boss_saturn", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_SATURN_TITLE", text = "saturn_lose_saturn_1", portrait = "boss_saturn", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_SATURN_TITLE", text = "saturn_win_saturn_1", portrait = "boss_saturn", button = "OK" },
            },
        },
        BOSS_13 = {
            enter = {
                { title = "characterMay", text = "blackness_greeting_may_1", portrait = "character_may_4", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_SAIMON", text = "blackness_greetingn_saimon_1", portrait = "character_simon_raid", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_LAZARUS_TITLE", text = "blackness_greeting_lazarus_2", portrait = "character_lazarus", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_SAIMON", text = "blackness_greeting_saimon_2", portrait = "character_simon_raid", button = "dlgStoryBtnMore" },
                { title = "BLACKNESS", text = "blackness_greeting_blackness_1", portrait = "boss_blackness", button = "dlgStoryBtnMore" },
                { title = "BLACKNESS", text = "blackness_enter_blackness_1", portrait = "boss_blackness", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "BLACKNESS", text = "blackness_lose_blackness_1", portrait = "boss_blackness", button = "OK" },
            },
            win = {
                { title = "characterSensei", text = "blackness_win_sensei", portrait = "character_sensei", button = "OK" },
            },
        },
        BOSS_14 = {
            enter = {
                { title = "RAIDBOSS_SAIMON", text = "dlgHunter_greeting_saimon_1", portrait = "character_simon_raid", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlgHunter_greeting_sensei_1", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_SAIMON", text = "dlgHunter_greeting_saimon_2", portrait = "character_simon_raid", button = "dlgStoryBtnMore" },
                { title = "characterMay", text = "dlgHunter_greeting_may_1", portrait = "character_may_4", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_SAIMON", text = "dlgHunter_greeting_sensei_2", portrait = "character_simon_raid", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_HUNTER", text = "dlgHunter_enter_hunter_1", portrait = "hunter_raid", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_HUNTER", text = "dlgHunter_loose_hunter_1", portrait = "hunter_raid", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_HUNTER", text = "dlgHunter_win_hunter_1", portrait = "hunter_raid", button = "OK" },
            },
        },
        BOSS_WHISPER = {
            enter = {
                { title = "RAIDBOSS_Fatum", text = "HW20Fatum1", portrait = "boss_fatum", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_Stone", text = "HW20Megalith1", portrait = "boss_crystal_halloween", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_Fatum", text = "HW20Fatum2", portrait = "boss_fatum", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_Arkhos", text = "HW20Arkhos1", portrait = "boss_arkhos_halloween", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_Fatum", text = "HW20Fatum3", portrait = "boss_fatum", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_WHISPER", text = "HW20Whisper1", portrait = "boss_whisper_24", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_Fatum", text = "HW20Fatum4", portrait = "boss_fatum", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_WHISPER", text = "HW20Whisper2", portrait = "boss_whisper_24", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_WHISPER", text = "dlgWhisperGreetings", portrait = "boss_whisper_24", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_WHISPER", text = "dlgWhisperWin", portrait = "boss_whisper_24", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_WHISPER", text = "dlgWhisperLost", portrait = "boss_whisper_24", button = "OK" },
            },
        },
        BOSS_SON_OF_THE_SUN = {
            enter = {
                { text = "dlg_CHN_NY25_Announce", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_CNY24", text = "dlg_CHN_NY25_Story_1", portrait = "boss_son_of_the_sun", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlg_CHN_NY25_Story_2", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_CNY24", text = "dlg_CHN_NY25_Story_3", portrait = "boss_son_of_the_sun", button = "dlgStoryBtnMore" },
                { title = "characterMay", text = "dlg_CHN_NY25_Story_4", portrait = "character_may_1", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_CNY24", text = "dlg_CHN_NY25_Story_5", portrait = "boss_son_of_the_sun", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_CNY24", text = "dlg_CHN_NY25_Story_6", portrait = "boss_son_of_the_sun", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlg_CHN_NY25_Story_7", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_CNY24", text = "dlg_CHN_NY25_Story_8", portrait = "boss_son_of_the_sun", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "characterSensei", text = "dlg_CHN_NY25_Loose_1", portrait = "character_sensei", button = "OK" },
            },
            win = {
                { title = "characterSensei", text = "dlg_CHN_NY25_Win_1", portrait = "character_sensei", button = "OK" },
            },
        },
        BOSS_RAVANA = {
            enter = {
                { title = "characterSensei", text = "dlgIE21AnnounceSensei_1", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "BOSS_RAVANA", text = "dlgIE21AnnounceBoss_1", portrait = "boss_ravana", button = "dlgStoryBtnMore" },
                { title = "characterMay", text = "dlgIE21AnnounceAssistant_1", portrait = "character_may_1", button = "dlgStoryBtnMore" },
                { title = "BOSS_RAVANA", text = "dlgIE21AnnounceBoss_2", portrait = "boss_ravana", button = "dlgStoryBtnMore" },
                { title = "BOSS_RAVANA", text = "dlgIE21AnnounceBoss_3", portrait = "boss_ravana", button = "dlgStoryBtnMore" },
                { title = "characterMay", text = "dlgIE21AnnounceAssistant_2", portrait = "character_may_1", button = "dlgStoryBtnMore" },
                { title = "characterMay", text = "dlgIE21AnnounceAssistant_3", portrait = "character_may_1", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "BOSS_RAVANA", text = "dlgIE21Boss_After_Loose", portrait = "boss_ravana", button = "OK" },
            },
            win = {
                { title = "BOSS_RAVANA", text = "dlgIE21Boss_After_Win", portrait = "boss_ravana", button = "OK" },
            },
        },
        BOSS_ADANTI = {
            enter = {
                { title = "characterMay", text = "dlg_American_25_Story_1", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlg_American_25_Story_2", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlg_American_25_Story_3", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "BOSS_BISON_21", text = "dlg_American_25_Story_4", portrait = "boss_bison", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlg_American_25_Story_5", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "BOSS_BISON_21", text = "dlg_American_25_Story_6", portrait = "boss_bison", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "BOSS_BISON_21", text = "dlg_American_25_Loose_1", portrait = "boss_bison", button = "OK" },
            },
            win = {
                { title = "BOSS_BISON_21", text = "dlg_American_25_Win_1", portrait = "boss_bison", button = "OK" },
            },
        },
        BOSS_LAMB = {
            enter = {
                { text = "MiniEventAnnounce", button = "dlgStoryBtnMore" },
                { title = "characterMiniEventPriestess", text = "MiniEventStory_1", portrait = "character_pristess", button = "dlgStoryBtnMore" },
                { title = "characterMiniEventPriestess", text = "MiniEventStory_2", portrait = "character_pristess", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_LAMB_Title", text = "MiniEventStory_EnterBattle", portrait = "boss_lamb", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_LAMB_Title", text = "MiniEventStory_Loss_1", portrait = "boss_lamb", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_LAMB_Title", text = "MiniEventStory_Win_1", portrait = "boss_lamb", button = "OK" },
            },
        },
        BOSS_RAKSHASA = {
            enter = {
                { title = "Title_Sitaram", text = "dlgIndia22Story_Sitaram_1", portrait = "character_sitaram_02", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlgIndia22Story_Sensei_1", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "Title_Sitaram", text = "dlgIndia22Story_Sitaram_2", portrait = "character_sitaram_01", button = "dlgStoryBtnMore" },
                { title = "characterMay", text = "dlgIndia22Story_May_1", portrait = "character_may_1", button = "dlgStoryBtnMore" },
                { title = "Title_Sitaram", text = "dlgIndia22Story_Sitaram_3", portrait = "character_sitaram_03", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_RAKSHASA_TITLE", text = "dlgIndia22Story_Rakshasa_1", portrait = "boss_rakshasa", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlgIndia22Story_Sensei_2", portrait = "character_sensei", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_RAKSHASA_TITLE", text = "dlgIndia22Story_Rakshasa_Lose", portrait = "boss_rakshasa", button = "OK" },
            },
            win = {
                { title = "characterSensei", text = "dlgIndia22Story_Sensei_Win", portrait = "character_sensei", button = "OK" },
            },
        },
        BOSS_HALLOWEEN_PUPPETEER = {
            enter = {
                { title = "RAIDBOSS_Arkhos", text = "dlgHW21StoryArkhos_1", portrait = "boss_arkhos", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlgHW21StorySensei_1", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "characterThief", text = "dlgHW21StoryThief_1", portrait = "character_thief_2", button = "dlgStoryBtnMore" },
                { title = "characterThief", text = "dlgHW21StoryThief_2", portrait = "character_thief_3", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_PUPPETEER", text = "dlgHW21StoryPuppeteer_1", portrait = "boss_puppeteer_hw21", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlgHW21StorySensei_2", portrait = "character_sensei", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_PUPPETEER", text = "dlgHW21LosePuppeteer_1", portrait = "boss_puppeteer_hw21", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_PUPPETEER", text = "dlgHW21WinPuppeteer_1", portrait = "boss_puppeteer_hw21", button = "OK" },
            },
        },
        BOSS_FARADEYA = {
            enter = {
                { title = "characterSensei", text = "dlgIndia24_Story_Sensei_1", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "tutorial_ascention_intro_title", text = "dlgIndia24_Story_Puppet_1", portrait = "character_puppeteer", button = "dlgStoryBtnMore" },
                { title = "tutorial_ascention_intro_title", text = "dlgIndia24_Story_Puppet_2", portrait = "character_puppeteer", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_FARADAY", text = "dlgIndia24_Story_Win_Faradeya_1", portrait = "character_faradaya", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "CharacterIndia24Nrityu", text = "dlgIndia24_Story_Loose_Nrityu_1", portrait = "character_nrityu", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_FARADAY", text = "dlgIndia24_Story_Win_Faradeya_1", portrait = "character_faradaya", button = "OK" },
            },
        },
        BOSS_BERSTUUK = {
            enter = {
                { text = "dlgBerstuuk_Announce", button = "dlgStoryBtnMore" },
                { title = "characterMay", text = "dlgBerstuuk_Story_1", portrait = "character_may_1", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlgBerstuuk_Story_2", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "characterThief", text = "dlgBerstuuk_Story_3", portrait = "character_thief_3", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlgBerstuuk_Story_4", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlgBerstuuk_Story_5", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "characterThief", text = "dlgBerstuuk_Story_6", portrait = "character_thief_3", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlgBerstuuk_Story_7", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_BERSTUUK", text = "dlgBerstuuk_Story_8", portrait = "boss_berstuuk", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlgBerstuuk_Story_9", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_BERSTUUK", text = "dlgBerstuuk_Story_10", portrait = "boss_berstuuk", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_BERSTUUK", text = "dlgBerstuuk_Loose_1", portrait = "boss_berstuuk", button = "OK" },
            },
            win = {
                { title = "RAIDBOSS_BERSTUUK", text = "dlgBerstuuk_Win_1", portrait = "boss_berstuuk", button = "OK" },
            },
        },
        BOSS_DANDY = {
            enter = {
                { title = "characterSensei", text = "dlgIndia24_Story_Sensei_2", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_DANDY", text = "dlgIndia24_Story_Dandy_1", portrait = "character_samson", button = "dlgStoryBtnMore" },
                { title = "tutorial_ascention_intro_title", text = "dlgIndia24_Story_Puppet_3", portrait = "character_puppeteer", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "tutorial_ascention_intro_title", text = "dlgIndia24_Story_Loose_Puppet_2", portrait = "character_puppeteer", button = "OK" },
            },
            win = {
                { title = "characterSensei", text = "dlgIndia24_Story_Win_Sensei_1", portrait = "character_sensei", button = "OK" },
            },
        },
        BOSS_SHURALE = {
            enter = {
                { text = "dlgShurale_Announce", button = "dlgStoryBtnMore" },
                { title = "characterThief", text = "dlg_NY25_Story_1", portrait = "character_thief_2", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlg_NY25_Story_2", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "characterThief", text = "dlg_NY25_Story_3", portrait = "character_thief_2", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlg_NY25_Story_4", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "characterThief", text = "dlg_NY25_Story_5", portrait = "character_thief_3", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlg_NY25_Story_6", portrait = "character_sensei", button = "dlgStoryBtnMore" },
                { title = "characterThief", text = "dlg_NY25_Story_7", portrait = "character_thief_3", button = "dlgStoryBtnMore" },
                { title = "RAIDBOSS_SHURALE", text = "dlg_NY25_Story_8", portrait = "boss_shurale_ny22", button = "dlgStoryBtnMore" },
                { title = "characterSensei", text = "dlg_NY25_Story_9", portrait = "character_sensei", button = "dlgStoryBtnFight", launch = true },
            },
            loss = {
                { title = "RAIDBOSS_SHURALE", text = "dlg_NY25_Loose_1", portrait = "boss_shurale_ny22", button = "OK" },
            },
            win = {
                { title = "characterSensei", text = "dlg_NY25_Win_1", portrait = "character_sensei", button = "OK" },
            },
        },
    },
}
