public class EquippedItemsStruct
{
	public ItemInfo PILJCAOFAED;

	public ItemInfo JGMLKIPCFII;

	public ItemInfo LKKFNMBCCDB;

	public ItemInfo FKMOLBBLKDA;

	public ItemInfo LGHMILECPLA;

	public ItemInfo ADBKGIBBNHJ;

	public ItemInfo LMIBBJIKLNO;

	public ItemInfo KKJJONOBHKI;

	public bool Compare(EquippedItemsStruct FNGODBOFAJD)
	{
		return FNGODBOFAJD.LKKFNMBCCDB == LKKFNMBCCDB && FNGODBOFAJD.FKMOLBBLKDA == FKMOLBBLKDA && FNGODBOFAJD.PILJCAOFAED == PILJCAOFAED && FNGODBOFAJD.JGMLKIPCFII == JGMLKIPCFII && FNGODBOFAJD.ADBKGIBBNHJ == ADBKGIBBNHJ && FNGODBOFAJD.LMIBBJIKLNO == LMIBBJIKLNO && FNGODBOFAJD.LGHMILECPLA == LGHMILECPLA;
	}
}
