public class QuestActionCheckPoint : QuestAction
{
	public override void DEJMHFMLKIC(QuestParameters GFIHPBCEEOB)
	{
		base.DEJMHFMLKIC(GFIHPBCEEOB);
		OIPDKFAJILO(GFIHPBCEEOB);
		ListSF.ELEBLBJKDBI().EJANJEEGOOE();
		OGIJONMKABB();
	}

	public void OIPDKFAJILO(QuestParameters GFIHPBCEEOB)
	{
		Roster nKGLHEGIKKP = ListSF.CCDKHLAMKKO();
		RosterQuest dKBDLDGOFDN = nKGLHEGIKKP.OOMJEHAKOBA(ONGHPGEIJEN);
		if (dKBDLDGOFDN == null)
		{
			dKBDLDGOFDN = ListSF.CCDKHLAMKKO().FLMIDLIKKOG(ONGHPGEIJEN, AEHNKDOJALB);
			CallEvent(2, dKBDLDGOFDN);
		}
		dKBDLDGOFDN.ECGFFBHMIIK(GFIHPBCEEOB, AMIMGEOENPL, Index);
		dKBDLDGOFDN.FileName = AEHNKDOJALB;
		ListSF.ELEBLBJKDBI().EJANJEEGOOE();
	}
}
