public enum ScreenFightType
{
	TYPE_INFO_NONE = 0,
	TYPE_INFO_VS = 1,
	TYPE_INFO_ROUND = 2,
	TYPE_INFO_SKIP_ROUND = 3,
	TYPE_INFO_FIGHT_RULE = 4,
	TYPE_INFO_FIGHT = 5,
	TYPE_INFO_PERFECT = 6,
	TYPE_INFO_COOL = 7,
	TYPE_INFO_ENEMIES = 8,
	TYPE_INFO_TIMESUP = 9,
	TYPE_INFO_RINGOUT = 10,
	TYPE_INFO_LOSE = 11,
	TYPE_INFO_WIN = 12
}
