public class TacticFactors
{
	public float EOGLBDCLMBM;

	public float KFMJMBANIGF;

	public float MGICNNKKCAN;

	public float DDGNCMJGDAG;

	public int OLCKGMBDGOG;

	public int DNPPDCPPGLM;

	public int JJDNDOLCMMN;

	public int KHDBLNPFDPE;

	public float AAKOCIPFDNM;

	public int NGMLGDJGBCD;

	public float DDFBIOFIDIH;

	public InfoAnimation HDCPIAPMFNO;

	public InfoAnimation PBDLLNEOIDG;

	public ModelStatistics FAKEJAAEPJG;

	public TacticFactors(ModelStatistics PNEPMGPIEIH, int IIAALGOFJJJ, int CPOOPPKHFHB)
	{
		DNPPDCPPGLM = IIAALGOFJJJ;
		JJDNDOLCMMN = CPOOPPKHFHB;
		FAKEJAAEPJG = PNEPMGPIEIH;
	}

	public TacticFactors(TacticFactors FJCBLOKOBBD)
	{
		CopyFrom(FJCBLOKOBBD);
	}

	public void CopyFrom(TacticFactors JFMALLHPPMH)
	{
		EOGLBDCLMBM = JFMALLHPPMH.EOGLBDCLMBM;
		KFMJMBANIGF = JFMALLHPPMH.KFMJMBANIGF;
		MGICNNKKCAN = JFMALLHPPMH.MGICNNKKCAN;
		DDGNCMJGDAG = JFMALLHPPMH.DDGNCMJGDAG;
		OLCKGMBDGOG = JFMALLHPPMH.OLCKGMBDGOG;
		DNPPDCPPGLM = JFMALLHPPMH.DNPPDCPPGLM;
		JJDNDOLCMMN = JFMALLHPPMH.JJDNDOLCMMN;
		KHDBLNPFDPE = JFMALLHPPMH.KHDBLNPFDPE;
		AAKOCIPFDNM = JFMALLHPPMH.AAKOCIPFDNM;
		FAKEJAAEPJG = JFMALLHPPMH.FAKEJAAEPJG;
		NGMLGDJGBCD = JFMALLHPPMH.NGMLGDJGBCD;
		DDFBIOFIDIH = JFMALLHPPMH.DDFBIOFIDIH;
		HDCPIAPMFNO = JFMALLHPPMH.HDCPIAPMFNO;
		PBDLLNEOIDG = JFMALLHPPMH.PBDLLNEOIDG;
	}
}
