using System.Runtime.CompilerServices;
using UnityEngine;

public class Vector2f
{
	public static readonly Vector2f FGGEKNJHPEG = new Vector2f();

	protected float PPKLGHELJIF;

	protected float DGGMCNNEGCA;

	public float NPKMJMCLDAH
	{
		get
		{
			return GILCBJJPKBK();
		}
		set
		{
			JPFALPBDBAP(value);
		}
	}

	public float IHAHIEHHNCG
	{
		get
		{
			return OBIMBNIBEFG();
		}
		set
		{
			IBNFLLGPOLD(value);
		}
	}

	public string OFIEAFIPOAM
	{
		get
		{
			return KCHEACEFEDA();
		}
	}

	public Vector2f(Vector2f PALAIICCALN)
	{
		PPKLGHELJIF = PALAIICCALN.GILCBJJPKBK();
		DGGMCNNEGCA = PALAIICCALN.OBIMBNIBEFG();
	}

	public Vector2f(float LHNJJFDIJKK = 0f, float FFFHIOALHGM = 0f)
	{
		PPKLGHELJIF = LHNJJFDIJKK;
		DGGMCNNEGCA = FFFHIOALHGM;
	}

	public Vector2f(Vector3f PMEFNGKHLII)
	{
		PPKLGHELJIF = PMEFNGKHLII.GILCBJJPKBK();
		DGGMCNNEGCA = PMEFNGKHLII.OBIMBNIBEFG();
	}

	public float GILCBJJPKBK()
	{
		return PPKLGHELJIF;
	}

	public void JPFALPBDBAP(float value)
	{
		PPKLGHELJIF = value;
	}

	public float OBIMBNIBEFG()
	{
		return DGGMCNNEGCA;
	}

	public void IBNFLLGPOLD(float value)
	{
		DGGMCNNEGCA = value;
	}

	[SpecialName]
	public static Vector2f MJOKEBGPHKB(Vector2f GIIIFLBEONP, Vector2f OIFPGODHFGH)
	{
		return new Vector2f(GIIIFLBEONP.GILCBJJPKBK() - OIFPGODHFGH.GILCBJJPKBK(), GIIIFLBEONP.OBIMBNIBEFG() - OIFPGODHFGH.OBIMBNIBEFG());
	}

	[SpecialName]
	public static Vector2f PHEFFKMOOCM(Vector2f GIIIFLBEONP, Vector2f OIFPGODHFGH)
	{
		return new Vector2f(GIIIFLBEONP.GILCBJJPKBK() + OIFPGODHFGH.GILCBJJPKBK(), GIIIFLBEONP.OBIMBNIBEFG() + OIFPGODHFGH.OBIMBNIBEFG());
	}

	[SpecialName]
	public static bool LFPMCJPCJBD(Vector2f GIIIFLBEONP, Vector2f OIFPGODHFGH)
	{
		if (object.ReferenceEquals(GIIIFLBEONP, OIFPGODHFGH))
		{
			return true;
		}
		if (object.ReferenceEquals(GIIIFLBEONP, null) || object.ReferenceEquals(OIFPGODHFGH, null))
		{
			return false;
		}
		return GIIIFLBEONP.GILCBJJPKBK() == OIFPGODHFGH.GILCBJJPKBK() && GIIIFLBEONP.OBIMBNIBEFG() == OIFPGODHFGH.OBIMBNIBEFG();
	}

	[SpecialName]
	public static bool GLCJKGIOIEC(Vector2f GIIIFLBEONP, Vector2f OIFPGODHFGH)
	{
		return !LFPMCJPCJBD(GIIIFLBEONP, OIFPGODHFGH);
	}

	[SpecialName]
	public static Vector3 op_Implicit(Vector2f BEHOPOPCJGB)
	{
		return new Vector3(BEHOPOPCJGB.GILCBJJPKBK(), BEHOPOPCJGB.OBIMBNIBEFG(), 0f);
	}

	public Vector2f Add(Vector2f PALAIICCALN)
	{
		PPKLGHELJIF += PALAIICCALN.GILCBJJPKBK();
		DGGMCNNEGCA += PALAIICCALN.OBIMBNIBEFG();
		return this;
	}

	public Vector2f Add(float LHNJJFDIJKK, float FFFHIOALHGM)
	{
		PPKLGHELJIF += LHNJJFDIJKK;
		DGGMCNNEGCA += FFFHIOALHGM;
		return this;
	}

	public Vector2f EHGLHOGAIDI(Vector2f PALAIICCALN)
	{
		PPKLGHELJIF -= PALAIICCALN.GILCBJJPKBK();
		DGGMCNNEGCA -= PALAIICCALN.OBIMBNIBEFG();
		return this;
	}

	public Vector2f Multiply(float LIAILCGJBDK)
	{
		PPKLGHELJIF *= LIAILCGJBDK;
		DGGMCNNEGCA *= LIAILCGJBDK;
		return this;
	}

	public void Set(Vector2f PALAIICCALN)
	{
		PPKLGHELJIF = PALAIICCALN.GILCBJJPKBK();
		DGGMCNNEGCA = PALAIICCALN.OBIMBNIBEFG();
	}

	public void Round(int CFCPPNJKNAL)
	{
		PPKLGHELJIF = Round(PPKLGHELJIF, CFCPPNJKNAL);
		DGGMCNNEGCA = Round(DGGMCNNEGCA, CFCPPNJKNAL);
	}

	public void MFDKMBLJNPA()
	{
		PPKLGHELJIF = Round(PPKLGHELJIF, 1f);
		DGGMCNNEGCA = Round(DGGMCNNEGCA, 1f);
	}

	public float DotProduct(Vector2f PIFPKKNEAID)
	{
		return PPKLGHELJIF * PIFPKKNEAID.GILCBJJPKBK() + DGGMCNNEGCA * PIFPKKNEAID.OBIMBNIBEFG();
	}

	public string KCHEACEFEDA()
	{
		return string.Format("[{0} {1}]", PPKLGHELJIF, DGGMCNNEGCA);
	}

	public override string ToString()
	{
		return string.Format("[Point: X={0}, Y={1}]", GILCBJJPKBK(), OBIMBNIBEFG());
	}

	public static float Round(float Value, float JMLMHGAMNKN)
	{
		return Mathf.Floor(Value * JMLMHGAMNKN + 0.5f) / JMLMHGAMNKN;
	}

	public static float JOIHAKCICMP(Vector3f AMNCLCPADOO, Vector3f IFIOLDFCLIE)
	{
		return Mathf.Sqrt((AMNCLCPADOO.GILCBJJPKBK() - IFIOLDFCLIE.GILCBJJPKBK()) * (AMNCLCPADOO.GILCBJJPKBK() - IFIOLDFCLIE.GILCBJJPKBK()) + (AMNCLCPADOO.OBIMBNIBEFG() - IFIOLDFCLIE.OBIMBNIBEFG()) * (AMNCLCPADOO.OBIMBNIBEFG() - IFIOLDFCLIE.OBIMBNIBEFG()));
	}

	public static float JOIHAKCICMP(Vector3f AMNCLCPADOO, Vector2f IFIOLDFCLIE)
	{
		return Mathf.Sqrt((AMNCLCPADOO.GILCBJJPKBK() - IFIOLDFCLIE.GILCBJJPKBK()) * (AMNCLCPADOO.GILCBJJPKBK() - IFIOLDFCLIE.GILCBJJPKBK()) + (AMNCLCPADOO.OBIMBNIBEFG() - IFIOLDFCLIE.OBIMBNIBEFG()) * (AMNCLCPADOO.OBIMBNIBEFG() - IFIOLDFCLIE.OBIMBNIBEFG()));
	}

	public static bool AOFPHLDNOIL(Vector3f IEKADOOKFKG, Vector3f LDKCOIHONPG, Vector3f AOOIPCJPALH, Vector3f IGMCGOFHHCJ, Vector3f DCJLKCFKCOM)
	{
		if ((IEKADOOKFKG.GILCBJJPKBK() == LDKCOIHONPG.GILCBJJPKBK() && IEKADOOKFKG.OBIMBNIBEFG() == LDKCOIHONPG.OBIMBNIBEFG()) || (AOOIPCJPALH.GILCBJJPKBK() == IGMCGOFHHCJ.GILCBJJPKBK() && AOOIPCJPALH.OBIMBNIBEFG() == IGMCGOFHHCJ.OBIMBNIBEFG()))
		{
			return false;
		}
		float num = LDKCOIHONPG.GILCBJJPKBK() - IEKADOOKFKG.GILCBJJPKBK();
		float num2 = LDKCOIHONPG.OBIMBNIBEFG() - IEKADOOKFKG.OBIMBNIBEFG();
		float num3 = IGMCGOFHHCJ.GILCBJJPKBK() - AOOIPCJPALH.GILCBJJPKBK();
		float num4 = IGMCGOFHHCJ.OBIMBNIBEFG() - AOOIPCJPALH.OBIMBNIBEFG();
		float num5 = IEKADOOKFKG.GILCBJJPKBK() - AOOIPCJPALH.GILCBJJPKBK();
		float num6 = IEKADOOKFKG.OBIMBNIBEFG() - AOOIPCJPALH.OBIMBNIBEFG();
		float num7 = num4 * num - num3 * num2;
		float num8 = num3 * num6 - num4 * num5;
		float num9 = num * num6 - num2 * num5;
		if (num7 == 0f)
		{
			if (num8 != 0f && num9 != 0f)
			{
				return false;
			}
			float num10;
			float num11;
			if (IEKADOOKFKG.GILCBJJPKBK() < LDKCOIHONPG.GILCBJJPKBK())
			{
				num10 = IEKADOOKFKG.GILCBJJPKBK();
				num11 = LDKCOIHONPG.GILCBJJPKBK();
			}
			else
			{
				num10 = LDKCOIHONPG.GILCBJJPKBK();
				num11 = IEKADOOKFKG.GILCBJJPKBK();
			}
			float num12;
			float num13;
			if (AOOIPCJPALH.GILCBJJPKBK() < IGMCGOFHHCJ.GILCBJJPKBK())
			{
				num12 = AOOIPCJPALH.GILCBJJPKBK();
				num13 = IGMCGOFHHCJ.GILCBJJPKBK();
			}
			else
			{
				num12 = IGMCGOFHHCJ.GILCBJJPKBK();
				num13 = AOOIPCJPALH.GILCBJJPKBK();
			}
			if (num10 > num13 || num12 > num11)
			{
				return false;
			}
			if (IEKADOOKFKG.OBIMBNIBEFG() < LDKCOIHONPG.OBIMBNIBEFG())
			{
				num10 = IEKADOOKFKG.OBIMBNIBEFG();
				num11 = LDKCOIHONPG.OBIMBNIBEFG();
			}
			else
			{
				num10 = LDKCOIHONPG.OBIMBNIBEFG();
				num11 = IEKADOOKFKG.OBIMBNIBEFG();
			}
			if (AOOIPCJPALH.OBIMBNIBEFG() < IGMCGOFHHCJ.OBIMBNIBEFG())
			{
				num12 = AOOIPCJPALH.OBIMBNIBEFG();
				num13 = IGMCGOFHHCJ.OBIMBNIBEFG();
			}
			else
			{
				num12 = IGMCGOFHHCJ.OBIMBNIBEFG();
				num13 = AOOIPCJPALH.OBIMBNIBEFG();
			}
			if (num10 > num13 || num12 > num11)
			{
				return false;
			}
			num7 = 1f;
		}
		num8 /= num7;
		num9 /= num7;
		if (num8 >= 0f && num8 <= 1f && num9 >= 0f && num9 <= 1f)
		{
			DCJLKCFKCOM.JPFALPBDBAP(IEKADOOKFKG.GILCBJJPKBK() + num8 * (LDKCOIHONPG.GILCBJJPKBK() - IEKADOOKFKG.GILCBJJPKBK()));
			DCJLKCFKCOM.IBNFLLGPOLD(IEKADOOKFKG.OBIMBNIBEFG() + num8 * (LDKCOIHONPG.OBIMBNIBEFG() - IEKADOOKFKG.OBIMBNIBEFG()));
			return true;
		}
		return false;
	}

	public static void JBLEOOBOCND(Vector3f MLGFPMDKOHD, Vector3f DMMNCDKPCCI, EquationLine EGKHHBMCGMK)
	{
		float num = JOIHAKCICMP(MLGFPMDKOHD, DMMNCDKPCCI);
		EGKHHBMCGMK.LHBNIMGFKIB = (MLGFPMDKOHD.OBIMBNIBEFG() - DMMNCDKPCCI.OBIMBNIBEFG()) / num;
		EGKHHBMCGMK.AAOIAEJJINO = (DMMNCDKPCCI.GILCBJJPKBK() - MLGFPMDKOHD.GILCBJJPKBK()) / num;
		EGKHHBMCGMK.ILHDJDNPFKH = 0f - (EGKHHBMCGMK.LHBNIMGFKIB * MLGFPMDKOHD.GILCBJJPKBK() + EGKHHBMCGMK.AAOIAEJJINO * MLGFPMDKOHD.OBIMBNIBEFG());
	}

	public static EquationLine JBLEOOBOCND(Vector3f MLGFPMDKOHD, Vector3f DMMNCDKPCCI)
	{
		EquationLine kEDCEHBPOIM = new EquationLine();
		JBLEOOBOCND(MLGFPMDKOHD, DMMNCDKPCCI, kEDCEHBPOIM);
		return kEDCEHBPOIM;
	}

	public static bool FLCEACOFEKB(Vector3f IEKADOOKFKG, Vector3f LDKCOIHONPG, Vector3f AOOIPCJPALH, Vector3f IGMCGOFHHCJ, Vector3f DCJLKCFKCOM)
	{
		if ((IEKADOOKFKG.GILCBJJPKBK() == LDKCOIHONPG.GILCBJJPKBK() && IEKADOOKFKG.OBIMBNIBEFG() == LDKCOIHONPG.OBIMBNIBEFG()) || (AOOIPCJPALH.GILCBJJPKBK() == IGMCGOFHHCJ.GILCBJJPKBK() && AOOIPCJPALH.OBIMBNIBEFG() == IGMCGOFHHCJ.OBIMBNIBEFG()))
		{
			return false;
		}
		float num = LDKCOIHONPG.GILCBJJPKBK() - IEKADOOKFKG.GILCBJJPKBK();
		float num2 = LDKCOIHONPG.OBIMBNIBEFG() - IEKADOOKFKG.OBIMBNIBEFG();
		float num3 = IGMCGOFHHCJ.GILCBJJPKBK() - AOOIPCJPALH.GILCBJJPKBK();
		float num4 = IGMCGOFHHCJ.OBIMBNIBEFG() - AOOIPCJPALH.OBIMBNIBEFG();
		float num5 = IEKADOOKFKG.GILCBJJPKBK() - AOOIPCJPALH.GILCBJJPKBK();
		float num6 = IEKADOOKFKG.OBIMBNIBEFG() - AOOIPCJPALH.OBIMBNIBEFG();
		float num7 = num4 * num - num3 * num2;
		float num8 = num3 * num6 - num4 * num5;
		float num9 = num * num6 - num2 * num5;
		if (num7 == 0f)
		{
			if (num8 != 0f && num9 != 0f)
			{
				return false;
			}
			float num10;
			float num11;
			if (IEKADOOKFKG.GILCBJJPKBK() < LDKCOIHONPG.GILCBJJPKBK())
			{
				num10 = IEKADOOKFKG.GILCBJJPKBK();
				num11 = LDKCOIHONPG.GILCBJJPKBK();
			}
			else
			{
				num10 = LDKCOIHONPG.GILCBJJPKBK();
				num11 = IEKADOOKFKG.GILCBJJPKBK();
			}
			float num12;
			float num13;
			if (AOOIPCJPALH.GILCBJJPKBK() < IGMCGOFHHCJ.GILCBJJPKBK())
			{
				num12 = AOOIPCJPALH.GILCBJJPKBK();
				num13 = IGMCGOFHHCJ.GILCBJJPKBK();
			}
			else
			{
				num12 = IGMCGOFHHCJ.GILCBJJPKBK();
				num13 = AOOIPCJPALH.GILCBJJPKBK();
			}
			if (num10 > num13 || num12 > num11)
			{
				return false;
			}
			if (IEKADOOKFKG.OBIMBNIBEFG() < LDKCOIHONPG.OBIMBNIBEFG())
			{
				num10 = IEKADOOKFKG.OBIMBNIBEFG();
				num11 = LDKCOIHONPG.OBIMBNIBEFG();
			}
			else
			{
				num10 = LDKCOIHONPG.OBIMBNIBEFG();
				num11 = IEKADOOKFKG.OBIMBNIBEFG();
			}
			if (AOOIPCJPALH.OBIMBNIBEFG() < IGMCGOFHHCJ.OBIMBNIBEFG())
			{
				num12 = AOOIPCJPALH.OBIMBNIBEFG();
				num13 = IGMCGOFHHCJ.OBIMBNIBEFG();
			}
			else
			{
				num12 = IGMCGOFHHCJ.OBIMBNIBEFG();
				num13 = AOOIPCJPALH.OBIMBNIBEFG();
			}
			if (num10 > num13 || num12 > num11)
			{
				return false;
			}
			num7 = 1f;
		}
		num8 /= num7;
		num9 /= num7;
		if (num8 >= 0f && num8 <= 1f && num9 >= 0f && num9 <= 1f)
		{
			DCJLKCFKCOM.JPFALPBDBAP(IEKADOOKFKG.GILCBJJPKBK() + num8 * (LDKCOIHONPG.GILCBJJPKBK() - IEKADOOKFKG.GILCBJJPKBK()));
			DCJLKCFKCOM.IBNFLLGPOLD(IEKADOOKFKG.OBIMBNIBEFG() + num8 * (LDKCOIHONPG.OBIMBNIBEFG() - IEKADOOKFKG.OBIMBNIBEFG()));
			return true;
		}
		return false;
	}

	public static bool IsDistanceStrike(float OIOMNNFMDOO, float JBLFLFOGDFI, EquationLine EGKHHBMCGMK, Vector3f NAAPALOFBCI, Vector3f _base, Vector3f ILENLCMAMBH, Vector3f PCLFFOBJJFO)
	{
		if (Mathf.Abs(OIOMNNFMDOO) <= JBLFLFOGDFI)
		{
			_base.JPFALPBDBAP(NAAPALOFBCI.GILCBJJPKBK() - OIOMNNFMDOO * EGKHHBMCGMK.LHBNIMGFKIB);
			_base.IBNFLLGPOLD(NAAPALOFBCI.OBIMBNIBEFG() - OIOMNNFMDOO * EGKHHBMCGMK.AAOIAEJJINO);
			return (((PCLFFOBJJFO.GILCBJJPKBK() <= _base.GILCBJJPKBK() && _base.GILCBJJPKBK() <= ILENLCMAMBH.GILCBJJPKBK()) || (ILENLCMAMBH.GILCBJJPKBK() <= _base.GILCBJJPKBK() && _base.GILCBJJPKBK() <= PCLFFOBJJFO.GILCBJJPKBK())) && ((PCLFFOBJJFO.OBIMBNIBEFG() <= _base.OBIMBNIBEFG() && _base.OBIMBNIBEFG() <= ILENLCMAMBH.OBIMBNIBEFG()) || (ILENLCMAMBH.OBIMBNIBEFG() <= _base.OBIMBNIBEFG() && _base.OBIMBNIBEFG() <= PCLFFOBJJFO.OBIMBNIBEFG()))) || (NAAPALOFBCI.GILCBJJPKBK() - ILENLCMAMBH.GILCBJJPKBK()) * (NAAPALOFBCI.GILCBJJPKBK() - ILENLCMAMBH.GILCBJJPKBK()) + (NAAPALOFBCI.OBIMBNIBEFG() - ILENLCMAMBH.OBIMBNIBEFG()) * (NAAPALOFBCI.OBIMBNIBEFG() - ILENLCMAMBH.OBIMBNIBEFG()) <= JBLFLFOGDFI * JBLFLFOGDFI || (NAAPALOFBCI.GILCBJJPKBK() - PCLFFOBJJFO.GILCBJJPKBK()) * (NAAPALOFBCI.GILCBJJPKBK() - PCLFFOBJJFO.GILCBJJPKBK()) + (NAAPALOFBCI.OBIMBNIBEFG() - PCLFFOBJJFO.OBIMBNIBEFG()) * (NAAPALOFBCI.OBIMBNIBEFG() - PCLFFOBJJFO.OBIMBNIBEFG()) <= JBLFLFOGDFI * JBLFLFOGDFI;
		}
		return false;
	}

	public static bool FLHCKLEBDDK(Vector3f HICHONIJHKL, Vector3f LNPFHLPCLOP, float KLDFJGIKIHG, Vector3f NMAJNHKJJEM, Vector3f ONNJMGGPHEL, float MGCKDDGGCBI, Vector3f DNJCFHNICBH, Vector3f LOFMLNLKFLB, EquationLine JHMHDMOADMA, EquationLine GIMOMPLMEJH)
	{
		float num = KLDFJGIKIHG + MGCKDDGGCBI;
		if (num == 0f)
		{
			if (FLCEACOFEKB(NMAJNHKJJEM, ONNJMGGPHEL, HICHONIJHKL, LNPFHLPCLOP, DNJCFHNICBH))
			{
				LOFMLNLKFLB.Set(DNJCFHNICBH);
				return true;
			}
			return false;
		}
		EquationLine kEDCEHBPOIM = ((GIMOMPLMEJH == null) ? JBLEOOBOCND(NMAJNHKJJEM, ONNJMGGPHEL) : GIMOMPLMEJH);
		float num2 = kEDCEHBPOIM.LHBNIMGFKIB * HICHONIJHKL.GILCBJJPKBK() + kEDCEHBPOIM.AAOIAEJJINO * HICHONIJHKL.OBIMBNIBEFG() + kEDCEHBPOIM.ILHDJDNPFKH;
		float num3 = kEDCEHBPOIM.LHBNIMGFKIB * LNPFHLPCLOP.GILCBJJPKBK() + kEDCEHBPOIM.AAOIAEJJINO * LNPFHLPCLOP.OBIMBNIBEFG() + kEDCEHBPOIM.ILHDJDNPFKH;
		if (0f <= num2 * num3 && num < Mathf.Abs(num2) && num < Mathf.Abs(num3))
		{
			return false;
		}
		EquationLine kEDCEHBPOIM2 = ((JHMHDMOADMA == null) ? JBLEOOBOCND(HICHONIJHKL, LNPFHLPCLOP) : JHMHDMOADMA);
		float num4 = kEDCEHBPOIM2.LHBNIMGFKIB * NMAJNHKJJEM.GILCBJJPKBK() + kEDCEHBPOIM2.AAOIAEJJINO * NMAJNHKJJEM.OBIMBNIBEFG() + kEDCEHBPOIM2.ILHDJDNPFKH;
		float num5 = kEDCEHBPOIM2.LHBNIMGFKIB * ONNJMGGPHEL.GILCBJJPKBK() + kEDCEHBPOIM2.AAOIAEJJINO * ONNJMGGPHEL.OBIMBNIBEFG() + kEDCEHBPOIM2.ILHDJDNPFKH;
		if (0f <= num4 * num5 && num < Mathf.Abs(num4) && num < Mathf.Abs(num5))
		{
			return false;
		}
		if (num4 * num5 < 0f && num2 * num3 < 0f)
		{
			float lIAILCGJBDK = num4 / (num4 - num5);
			DNJCFHNICBH.Set(Vector3f.MJOKEBGPHKB(ONNJMGGPHEL, NMAJNHKJJEM));
			DNJCFHNICBH.Multiply(lIAILCGJBDK);
			DNJCFHNICBH.Add(NMAJNHKJJEM);
			LOFMLNLKFLB.Set(DNJCFHNICBH);
			return true;
		}
		if (IsDistanceStrike(num2, num, kEDCEHBPOIM, HICHONIJHKL, LOFMLNLKFLB, NMAJNHKJJEM, ONNJMGGPHEL))
		{
			DNJCFHNICBH.Set(HICHONIJHKL);
			return true;
		}
		if (IsDistanceStrike(num3, num, kEDCEHBPOIM, LNPFHLPCLOP, LOFMLNLKFLB, NMAJNHKJJEM, ONNJMGGPHEL))
		{
			DNJCFHNICBH.Set(LNPFHLPCLOP);
			return true;
		}
		if (IsDistanceStrike(num4, num, kEDCEHBPOIM2, NMAJNHKJJEM, LOFMLNLKFLB, HICHONIJHKL, LNPFHLPCLOP))
		{
			DNJCFHNICBH.Set(NMAJNHKJJEM);
			LOFMLNLKFLB.Set(NMAJNHKJJEM);
			return true;
		}
		if (IsDistanceStrike(num5, num, kEDCEHBPOIM2, ONNJMGGPHEL, LOFMLNLKFLB, HICHONIJHKL, LNPFHLPCLOP))
		{
			DNJCFHNICBH.Set(ONNJMGGPHEL);
			LOFMLNLKFLB.Set(ONNJMGGPHEL);
			return true;
		}
		return false;
	}

	public static float LDKCDLFIDHL(Vector2f LHBNIMGFKIB, Vector2f AAOIAEJJINO)
	{
		return (AAOIAEJJINO.GILCBJJPKBK() - LHBNIMGFKIB.GILCBJJPKBK()) * (AAOIAEJJINO.GILCBJJPKBK() - LHBNIMGFKIB.GILCBJJPKBK()) + (AAOIAEJJINO.OBIMBNIBEFG() - LHBNIMGFKIB.OBIMBNIBEFG()) * (AAOIAEJJINO.OBIMBNIBEFG() - LHBNIMGFKIB.OBIMBNIBEFG());
	}

	public static float GetAngle2DDegreeSigned(Vector2f LHBNIMGFKIB, Vector2f AAOIAEJJINO)
	{
		return GetAngle2DRadianSigned(LHBNIMGFKIB, AAOIAEJJINO) * 57.29578f;
	}

	public static float GetAngle2DRadianSigned(Vector2f LHBNIMGFKIB, Vector2f AAOIAEJJINO)
	{
		float num = LHBNIMGFKIB.PPKLGHELJIF * AAOIAEJJINO.DGGMCNNEGCA - LHBNIMGFKIB.DGGMCNNEGCA * AAOIAEJJINO.PPKLGHELJIF;
		float num2 = LHBNIMGFKIB.PPKLGHELJIF * AAOIAEJJINO.PPKLGHELJIF + LHBNIMGFKIB.DGGMCNNEGCA * AAOIAEJJINO.DGGMCNNEGCA;
		float num3 = 1f / Mathf.Sqrt(num * num + num2 * num2);
		return Mathf.Atan2(num * num3, num2 * num3);
	}
}
