public enum VisualObjectType
{
	VISUAL_OBJECT_ENCHANTMENT_BUTTON = 0,
	VISUAL_OBJECT_FORGE_APPLY_BUTTON = 1,
	VISUAL_OBJECT_SHOP_WEAPON_SLIDER = 2,
	VISUAL_OBJECT_SHOP_ARMOR_SLIDER = 3,
	VISUAL_OBJECT_SHOP_FORGE_ROLL = 4,
	VISUAL_OBJECT_SHOP_PERKS_INFO_SPRITE = 5,
	VISUAL_OBJECT_SHOP_COMBO_PERK_ITEM = 6,
	VISUAL_OBJECT_SHOP_PERKS_SLIDER = 7
}
