#!/usr/bin/env python3
"""Generate static Titan reward names from the archived localization tables."""

from __future__ import annotations

import argparse
from pathlib import Path
import xml.etree.ElementTree as ET
from DE128Localization import key_module, section_outputs, write_outputs


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "Assets/DExml/localizations"
OWNER_ENGLISH = ROOT / "ResearchSources/de128_assets/gamedata/localizations/eng.xml"
TARGET = ROOT / "Mods/de128/scripts/content/titan_reward_text.lua"
KEYS = ("BODY_TITAN", "HEAD_TITAN", "RANGED_TITANS_HARPOON", "MAGIC_MIND_THROW")


def read_names(path: Path) -> dict[str, str]:
    words = {node.get("Title"): node.text or "" for node in ET.parse(path).iter("Word")}
    missing = [key for key in KEYS if not words.get(key)]
    if missing:
        raise ValueError(f"{path}: missing Titan names {missing}")
    return {key: words[key] for key in KEYS}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    languages = sorted(SOURCE.glob("*.xml"))
    if len(languages) != 14:
        raise ValueError(f"Expected 14 archived languages, found {len(languages)}")
    if read_names(SOURCE / "eng.xml") != read_names(OWNER_ENGLISH):
        raise ValueError("Owner English Titan names differ from the historical archive")
    values = {source.stem: read_names(source) for source in languages}
    outputs = section_outputs('GENERATED Titan rewards (Tools/GenerateDE128TitanRewardText.py)', values, 'titan_reward.')
    outputs[TARGET] = '-- GENERATED by Tools/GenerateDE128TitanRewardText.py; do not edit by hand.\n' + key_module(KEYS, 'titan_reward.')
    if args.check:
        for path, expected in outputs.items():
            if not path.exists() or path.read_text(encoding='utf-8') != expected:
                raise ValueError(f"Generated Titan reward names differ: {path}")
    else:
        write_outputs(outputs)
    print(f"Verified {len(languages)} languages and {len(KEYS)} Titan reward names")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
