#!/usr/bin/env python3
"""Generate DE128's Challenger battle, opponent and weapon-drop text.

Source: the archived localization tables (Assets/DExml/localizations, 14
languages). The owner English table must match the archive for every key.
Weapon names and OK are copied too, so the drop dialog keeps its archived
wording even where a core translation differs.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import xml.etree.ElementTree as ET
from DE128Localization import key_module, section_outputs, write_outputs


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "Assets/DExml/localizations"
OWNER_ENGLISH = ROOT / "ResearchSources/de128_assets/gamedata/localizations/eng.xml"
TARGET = ROOT / "Mods/de128/scripts/content/challenger_text.lua"
PREFIX = "challenger."
KEYS = (
    # Battle aliases (Trickster's alias differs from his opponent name).
    "characterTrickster",
    # Opponent names; the other six also serve as battle aliases.
    "NAME_TRICKSTER", "NAME_HAWK", "NAME_ROSE", "NAME_FISHER", "NAME_OUTCAST", "NAME_RONIN", "NAME_IM_STRANGER",
    "TRICKSTER_Title", "HAWK_Title", "ROSE_Title", "FISHER_Title", "OUTCAST_Title", "RONIN_Title", "NOVA_Title",
    "descTrickster", "descHawk", "descRose", "descFisher", "descOutcast", "descRonin", "descNova",
    "Trickster_drop", "Hawk_drop", "Rose_drop", "Fisher_drop", "Outcast_drop", "Ronin_drop", "Nova_drop",
    "WEAPON_NUNCHAKU", "WEAPON_NAGINATA", "WEAPON_KATANA", "WEAPON_WANDERER_STAFF",
    "WEAPON_HEAVY_KUSARIGAMA", "WEAPON_DADAO_JANISSARY", "WEAPON_STRANGER_KNUCKLES",
    "OK",
)


def read_words(path: Path) -> dict[str, str]:
    words: dict[str, str] = {}
    for node in ET.parse(path).iter("Word"):
        words.setdefault(node.get("Title"), node.text or "")
    missing = [key for key in KEYS if not words.get(key)]
    if missing:
        raise ValueError(f"{path}: missing Challenger text {missing}")
    return {key: words[key] for key in KEYS}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    languages = sorted(SOURCE.glob("*.xml"))
    if len(languages) != 14:
        raise ValueError(f"Expected 14 archived languages, found {len(languages)}")
    if read_words(SOURCE / "eng.xml") != read_words(OWNER_ENGLISH):
        raise ValueError("Owner English Challenger text differs from the historical archive")
    values = {source.stem: read_words(source) for source in languages}
    outputs = section_outputs("GENERATED Challengers (Tools/GenerateDE128ChallengerText.py)", values, PREFIX)
    module = key_module(KEYS, PREFIX).replace("return text\n", (
        "-- Battle and opponent fields take the qualified runtime key, not a handle.\n"
        "function text.key(key)\n"
        "    assert(text[key], \"Unknown Challenger text key \" .. tostring(key))\n"
        "    return (sf2.mod.id .. \":localization/" + PREFIX + "\" .. key):lower()\n"
        "end\n"
        "return text\n"))
    outputs[TARGET] = "-- GENERATED by Tools/GenerateDE128ChallengerText.py; do not edit by hand.\n" + module
    if args.check:
        for path, expected in outputs.items():
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                raise ValueError(f"Generated Challenger text differs: {path}")
    else:
        write_outputs(outputs)
    print(f"Verified {len(languages)} languages and {len(KEYS)} Challenger text keys")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
