"""Import owner-supplied DENew buttons into DE128; --check verifies reproducibility.

Read the shipped TAR metadata (not archival Unity sprite YAML) to match exact
core members and preserve their layout size. PNGs are copied without editing.
Requires the repository's Python 3.12 Pillow/lz4 packages.
"""
from pathlib import Path
import argparse
import json
import sys
import tarfile

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "Tools/python-packages"))
import lz4.frame
from PIL import Image

DROP = ROOT / "ResearchSources/DENew/Buttons"
MOD = ROOT / "Mods/de128"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    images = {p.stem: p for p in sorted(DROP.rglob("*.png"))}
    assert len(images) == 296, "Review changed button drop before importing"
    outputs = {}
    targets = {}
    used = set()
    catalog = json.loads((ROOT / "Assets/Resources/SF2Content/Art/catalog.json").read_text())
    for bundle in catalog["bundles"]:
        if not any("battlebtn" in a["address"].lower() for a in bundle["assets"]):
            continue
        archive = ROOT / "Assets/StreamingAssets/SF2Content/ArtBundles" / bundle["file"]
        with lz4.frame.open(archive) as stream, tarfile.open(fileobj=stream, mode="r|") as tar:
            for entry in tar:
                if not entry.name.endswith(".meta") or "battlebtn" not in entry.name.lower():
                    continue
                meta = dict(line.split("=", 1) for line in tar.extractfile(entry).read().decode().splitlines() if "=" in line)
                name = meta.get("name")
                if name not in images:
                    continue
                source = images[name]
                with Image.open(source) as image:
                    width, height = image.size
                rect = [float(v) for v in meta["rect"].split(",")]
                scale = width / rect[2]
                assert abs(scale - height / rect[3]) < 0.00001, f"Aspect ratio changed: {name}"
                address = meta["address"]
                leaf = address.rsplit("/", 1)[-1]
                member = name[len(leaf) + 1:] if name.startswith(leaf + ".") else name
                target = "core:" + address + "." + member
                key = (leaf + "." + member).lower()
                replacement = "sprites/map_buttons/" + key
                texture = "textures/map_buttons/" + name.lower() + ".png"
                body = (f"type=sprite\ntexture={texture}\npixels_per_unit={float(meta['pixels_per_unit']) * scale:g}\n"
                        f"pivot=[{meta['pivot']}]\n")
                path = MOD / "assets" / (replacement + ".asset")
                assert path not in outputs or outputs[path] == body.encode(), f"Conflicting geometry: {target}"
                outputs[path] = body.encode()
                outputs[MOD / "assets" / texture] = source.read_bytes()
                targets[target] = replacement
                used.add(name)

    # Existing DE-owned raid and challenger IDs stay stable for their consumers.
    owned = 0
    for category in ("underworld", "challenger"):
        for descriptor in sorted((MOD / "assets/sprites" / category).glob("battlebtn*.asset")):
            atlas, state = descriptor.stem.rsplit("_", 1)
            matches = [p for name, p in images.items()
                       if name.split(".")[0].lower() == atlas + state and name.split(".")[1].startswith(state + "_")]
            assert len(matches) == 1, descriptor
            source = matches[0]
            with Image.open(source) as image:
                assert image.size == (600, 600), source
            texture = f"textures/{category}/{descriptor.stem}.png"
            outputs[descriptor] = f"type=sprite\ntexture={texture}\npixels_per_unit=200\n".encode()
            outputs[MOD / "assets" / texture] = source.read_bytes()
            used.add(source.stem)
            owned += 1

    lua = ['-- Generated by Tools/ImportDE128MapButtons.py. PNGs retain their source pixels.', 'local sf2 = require("sf2")', 'local replacements = {']
    lua += [f'    {{ "{target}", "{replacement}" }},' for target, replacement in sorted(targets.items())]
    lua += ['}', 'for _, row in ipairs(replacements) do', '    sf2.assets.replace { target = row[1], replacement = row[2] }', 'end', '']
    outputs[MOD / "scripts/content/map_buttons.lua"] = "\n".join(lua).encode()
    report = {"core_replacements": len(targets), "owned_buttons": owned,
              "used_images": len(used), "unused_images": sorted(images.keys() - used),
              "core_targets": sorted(targets)}
    outputs[MOD / "MAP_BUTTONS.json"] = (json.dumps(report, indent=2) + "\n").encode()
    for path, content in outputs.items():
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
        assert path.read_bytes() == content, f"Outdated: {path}"
    print(f"Verified {len(targets)} core replacements, {owned} DE-owned states; {len(used)}/296 source images used.")
    print("Unused images are listed in Mods/de128/MAP_BUTTONS.json.")


if __name__ == "__main__":
    main()
