"""Copy DENew menu, VS and loading art into DE128; --check verifies exact source bytes."""
import argparse
import json
import struct
import zlib
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
DROP = ROOT / "ResearchSources/DENew/Output"
MOD = ROOT / "Mods/de128"

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs, targets, used = {}, {}, set()
    for source in sorted(DROP.glob("MenuButtons.*.png")):
        original = ROOT / "Assets/Resources/ui/atlases" / (source.stem + ".asset")
        if not original.exists():
            continue
        size = struct.unpack(">II", source.read_bytes()[16:24])
        assert size == ((500, 500) if "Highlight_menu" in source.name else (556, 556)), source
        name = source.stem.lower()
        target = "core:ui/atlases/" + name
        replacement = "sprites/menu/" + name
        texture = "textures/menu/" + name + ".png"
        outputs[MOD / "assets" / texture] = source.read_bytes()
        outputs[MOD / "assets" / (replacement + ".asset")] = (f"type=sprite\ntexture={texture}\npixels_per_unit=200\npivot=[0.5,0.5]\n").encode()
        targets[target] = replacement
        used.add(source.name)
    # The prefab animates two independent panels. Both descriptors share one PNG,
    # exposing complementary halves without rewriting or resampling the source.
    # The fight loader (map EnterScreen and the loader into and out of fights: brown bg.png)
    # and the launch splash (Preloader.png) use the same two-panel geometry.
    for source, texture, stem in ((DROP / "VS_Fon.png", "vs_fon", "vs_fon"),
                                  (DROP.parent / "bg.png", "loading", "loading"),
                                  (DROP / "Preloader.png", "start_loading", "startloading")):
        assert struct.unpack(">II", source.read_bytes()[16:24]) == (2560, 1080), source
        outputs[MOD / f"assets/textures/menu/{texture}.png"] = source.read_bytes()
        used.add(source.name)
        for side, x in (("left", 0), ("right", 1280)):
            name = f"{stem}_{side}"
            original = ROOT / "Assets/Resources/ui/fullscreen" / (name + ".img.asset")
            assert original.exists(), original
            replacement = "sprites/menu/" + name
            outputs[MOD / "assets" / (replacement + ".asset")] = (f"type=sprite\ntexture=textures/menu/{texture}.png\nrect=[{x},0,1280,1080]\npixels_per_unit=100\npivot=[0.5,0.5]\n").encode()
            targets["core:ui/fullscreen/" + name + ".img"] = replacement
    # Moving between menu screens shows the Preloader splash through Eclipse's menu-loader
    # panels (core aliases of the loading panels, so they have no .img.asset of their own).
    for side, x in (("left", 0), ("right", 1280)):
        name = f"menu_loading_{side}"
        replacement = "sprites/menu/" + name
        outputs[MOD / "assets" / (replacement + ".asset")] = (f"type=sprite\ntexture=textures/menu/start_loading.png\nrect=[{x},0,1280,1080]\npixels_per_unit=100\npivot=[0.5,0.5]\n").encode()
        targets["core:ui/fullscreen/" + name + ".img"] = replacement
    # DENew's full-screen splash already contains the complete logo. The loader
    # also draws the recovered Logo.left/right images; replace those with a
    # transparent sprite in this content pack rather than hiding base-game UI.
    def chunk(kind, data):
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data))
    transparent = (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", 1, 1, 8, 6, 0, 0, 0))
                   + chunk(b"IDAT", zlib.compress(b"\x00\x00\x00\x00\x00")) + chunk(b"IEND", b""))
    outputs[MOD / "assets/textures/menu/transparent.png"] = transparent
    outputs[MOD / "assets/sprites/menu/loader_logo.asset"] = b"type=sprite\ntexture=textures/menu/transparent.png\npixels_per_unit=100\npivot=[0.5,0.5]\n"
    for side in ("left", "right"):
        targets[f"core:textures/logos/logo.{side}"] = "sprites/menu/loader_logo"
    assert len(targets) == 23, "Review changed UI resource coverage"
    lua = ['-- Generated by Tools/ImportDE128MenuArt.py.', 'local sf2 = require("sf2")', 'local replacements = {']
    lua += [f'    {{ "{a}", "{b}" }},' for a, b in sorted(targets.items())]
    lua += ['}', 'for _, row in ipairs(replacements) do', '    sf2.assets.replace { target = row[1], replacement = row[2] }', 'end', '']
    outputs[MOD / "scripts/content/menu_art.lua"] = "\n".join(lua).encode()
    report = {"core_targets": sorted(targets), "used_images": sorted(used), "unused_images": sorted(p.name for p in DROP.glob("*.png") if p.name not in used)}
    outputs[MOD / "MENU_ART.json"] = (json.dumps(report, indent=2) + "\n").encode()
    for path, content in outputs.items():
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
        assert path.read_bytes() == content, path
    print(f"Verified {len(targets)} UI replacements from {len(used)} source PNGs.")

if __name__ == "__main__":
    main()
