"""Copy DENew menu and VS art into DE128; --check verifies exact source bytes."""
import argparse
import json
import struct
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
DROP = ROOT / "ResearchSources/DENew/Output"
MOD = ROOT / "Mods/de128"

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs, targets, used = {}, {}, set()
    for source in sorted(DROP.glob("MenuButtons.*.png")):
        original = ROOT / "Assets/Resources/ui/atlases" / (source.stem + ".asset")
        if not original.exists():
            continue
        size = struct.unpack(">II", source.read_bytes()[16:24])
        assert size == ((500, 500) if "Highlight_menu" in source.name else (556, 556)), source
        name = source.stem.lower()
        target = "core:ui/atlases/" + name
        replacement = "sprites/menu/" + name
        texture = "textures/menu/" + name + ".png"
        outputs[MOD / "assets" / texture] = source.read_bytes()
        outputs[MOD / "assets" / (replacement + ".asset")] = (f"type=sprite\ntexture={texture}\npixels_per_unit=200\npivot=[0.5,0.5]\n").encode()
        targets[target] = replacement
        used.add(source.name)
    # The prefab animates two independent panels. Both descriptors share one PNG,
    # exposing complementary halves without rewriting or resampling the source.
    source = DROP / "VS_Fon.png"
    assert struct.unpack(">II", source.read_bytes()[16:24]) == (2560, 1080), source
    outputs[MOD / "assets/textures/menu/vs_fon.png"] = source.read_bytes()
    used.add(source.name)
    for side, x in (("left", 0), ("right", 1280)):
        name = "vs_fon_" + side
        original = ROOT / "Assets/Resources/ui/fullscreen" / (name + ".img.asset")
        assert original.exists(), original
        replacement = "sprites/menu/" + name
        outputs[MOD / "assets" / (replacement + ".asset")] = (f"type=sprite\ntexture=textures/menu/vs_fon.png\nrect=[{x},0,1280,1080]\npixels_per_unit=100\npivot=[0.5,0.5]\n").encode()
        targets["core:ui/fullscreen/" + name + ".img"] = replacement
    assert len(targets) == 15, "Review changed UI resource coverage"
    lua = ['-- Generated by Tools/ImportDE128MenuArt.py.', 'local sf2 = require("sf2")', 'local replacements = {']
    lua += [f'    {{ "{a}", "{b}" }},' for a, b in sorted(targets.items())]
    lua += ['}', 'for _, row in ipairs(replacements) do', '    sf2.assets.replace { target = row[1], replacement = row[2] }', 'end', '']
    outputs[MOD / "scripts/content/menu_art.lua"] = "\n".join(lua).encode()
    report = {"core_targets": sorted(targets), "used_images": sorted(used), "unused_images": sorted(p.name for p in DROP.glob("*.png") if p.name not in used)}
    outputs[MOD / "MENU_ART.json"] = (json.dumps(report, indent=2) + "\n").encode()
    for path, content in outputs.items():
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
        assert path.read_bytes() == content, path
    print(f"Verified {len(targets)} UI replacements from {len(used)} source PNGs.")

if __name__ == "__main__":
    main()
