"""Stage portable texture/audio/font sources for Unity-native art consolidation.

Sprite geometry is serialized by Unity, never by this script. Python 3.12 and
the existing Tools/python-packages UnityPy installation are required.
"""
from pathlib import Path
import argparse
import json
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "Tools/python-packages"))
import UnityPy


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--fixture", required=True, type=Path)
    args = parser.parse_args()
    fixture = args.fixture.resolve()
    bundles = []
    for source in sorted(args.source.iterdir(), key=lambda p: p.name.lower()):
        if not source.is_file() or source.suffix: continue
        env = UnityPy.load(str(source))
        objects = {}
        for address, obj in env.container.items():
            obj = obj.deref()
            if obj.type.name in {"Texture2D", "AudioClip", "Font"}:
                objects.setdefault((obj.assets_file.name, obj.path_id), (obj, address))
        if not objects: continue
        records = []
        addresses = sorted(set(env.container.keys()))
        for obj, address in objects.values():
            data = obj.read()
            kind = obj.type.name
            name = re.sub(r'[^a-zA-Z0-9._-]', '_', data.m_Name)
            relative = f"Assets/Resources/SF2Content/Art/{source.name}/{kind}/{name}_{obj.path_id}"
            record = dict(address=address, kind=kind, path="", name=data.m_Name)
            if kind == "Texture2D":
                if data.m_Width == 0 or data.m_Height == 0: continue # Dynamic font atlases are generated by Unity.
                relative += ".png"
                target = fixture / relative
                target.parent.mkdir(parents=True, exist_ok=True)
                if not target.exists(): data.image.save(target)
                settings = data.m_TextureSettings
                record.update(filter=int(settings.m_FilterMode), aniso=int(settings.m_Aniso),
                    wrapU=int(getattr(settings, 'm_WrapU', 1)), wrapV=int(getattr(settings, 'm_WrapV', 1)),
                    mipmaps=bool(getattr(data, 'm_MipCount', 1) > 1))
            elif kind == "Font":
                if not data.m_FontData: raise ValueError(f"Font has no portable data: {address}")
                relative += ".ttf"
                target = fixture / relative
                target.parent.mkdir(parents=True, exist_ok=True)
                if not target.exists(): target.write_bytes(bytes(data.m_FontData))
            else:
                samples = data.samples
                if len(samples) != 1: raise ValueError(f"Expected one audio stream: {address}")
                sample_name, payload = next(iter(samples.items()))
                relative += Path(sample_name).suffix
                target = fixture / relative
                target.parent.mkdir(parents=True, exist_ok=True)
                if not target.exists(): target.write_bytes(payload)
            record['path'] = relative
            records.append(record)
        if records:
            bundles.append(dict(name=source.name, source=str(source.resolve()), sources=records, addresses=addresses))
        print(source.name, len(records), flush=True)
    manifest = fixture / "native-art-input.json"
    manifest.write_text(json.dumps(dict(bundles=bundles), indent=2), encoding="utf-8")
    print(f"Staged {sum(len(b['sources']) for b in bundles)} portable sources in {fixture}", flush=True)


if __name__ == '__main__': main()
